/**
 * Static geo data for /api/v1/geo endpoints.
 * No DB dependency - used for country/state dropdowns in unified location UI.
 */

export interface CountryItem {
  code: string;
  name: string;
}

export interface StateItem {
  code: string;
  name: string;
}

/** Static country list - extend as needed */
export const GEO_COUNTRIES: CountryItem[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AU', name: 'Australia' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'CA', name: 'Canada' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'IN', name: 'India' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'NP', name: 'Nepal' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'CN', name: 'China' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'South Korea' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'EG', name: 'Egypt' },
  { code: 'QA', name: 'Qatar' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'OM', name: 'Oman' },
  { code: 'BH', name: 'Bahrain' },
];

/** States/provinces by country code - no DB, static only */
export const GEO_STATES_BY_COUNTRY: Record<string, StateItem[]> = {
  BD: [
    { code: 'BAR', name: 'Barishal' },
    { code: 'CHI', name: 'Chattogram' },
    { code: 'DHA', name: 'Dhaka' },
    { code: 'KHU', name: 'Khulna' },
    { code: 'MYM', name: 'Mymensingh' },
    { code: 'RAJ', name: 'Rajshahi' },
    { code: 'RAN', name: 'Rangpur' },
    { code: 'SYL', name: 'Sylhet' },
  ],
  IN: [
    { code: 'AN', name: 'Andaman and Nicobar Islands' },
    { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' },
    { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' },
    { code: 'CH', name: 'Chandigarh' },
    { code: 'CT', name: 'Chhattisgarh' },
    { code: 'DL', name: 'Delhi' },
    { code: 'GA', name: 'Goa' },
    { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' },
    { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JK', name: 'Jammu and Kashmir' },
    { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' },
    { code: 'KL', name: 'Kerala' },
    { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' },
    { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' },
    { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' },
    { code: 'OR', name: 'Odisha' },
    { code: 'PB', name: 'Punjab' },
    { code: 'RJ', name: 'Rajasthan' },
    { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TG', name: 'Telangana' },
    { code: 'TR', name: 'Tripura' },
    { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UT', name: 'Uttarakhand' },
    { code: 'WB', name: 'West Bengal' },
  ],
  US: [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
    { code: 'DC', name: 'District of Columbia' },
  ],
  CA: [
    { code: 'AB', name: 'Alberta' },
    { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' },
    { code: 'NS', name: 'Nova Scotia' },
    { code: 'NT', name: 'Northwest Territories' },
    { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' },
    { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],
  GB: [
    { code: 'ENG', name: 'England' },
    { code: 'SCT', name: 'Scotland' },
    { code: 'WLS', name: 'Wales' },
    { code: 'NIR', name: 'Northern Ireland' },
  ],
  AU: [
    { code: 'ACT', name: 'Australian Capital Territory' },
    { code: 'NSW', name: 'New South Wales' },
    { code: 'NT', name: 'Northern Territory' },
    { code: 'QLD', name: 'Queensland' },
    { code: 'SA', name: 'South Australia' },
    { code: 'TAS', name: 'Tasmania' },
    { code: 'VIC', name: 'Victoria' },
    { code: 'WA', name: 'Western Australia' },
  ],
  DE: [
    { code: 'BW', name: 'Baden-Württemberg' },
    { code: 'BY', name: 'Bayern' },
    { code: 'BE', name: 'Berlin' },
    { code: 'BB', name: 'Brandenburg' },
    { code: 'HB', name: 'Bremen' },
    { code: 'HH', name: 'Hamburg' },
    { code: 'HE', name: 'Hessen' },
    { code: 'MV', name: 'Mecklenburg-Vorpommern' },
    { code: 'NI', name: 'Niedersachsen' },
    { code: 'NW', name: 'Nordrhein-Westfalen' },
    { code: 'RP', name: 'Rheinland-Pfalz' },
    { code: 'SL', name: 'Saarland' },
    { code: 'SN', name: 'Sachsen' },
    { code: 'ST', name: 'Sachsen-Anhalt' },
    { code: 'SH', name: 'Schleswig-Holstein' },
    { code: 'TH', name: 'Thüringen' },
  ],
  FR: [
    { code: 'ARA', name: 'Auvergne-Rhône-Alpes' },
    { code: 'BFC', name: 'Bourgogne-Franche-Comté' },
    { code: 'BRE', name: 'Bretagne' },
    { code: 'CVL', name: 'Centre-Val de Loire' },
    { code: 'COR', name: 'Corse' },
    { code: 'GES', name: 'Grand Est' },
    { code: 'HDF', name: 'Hauts-de-France' },
    { code: 'IDF', name: 'Île-de-France' },
    { code: 'NOR', name: 'Normandie' },
    { code: 'NAQ', name: 'Nouvelle-Aquitaine' },
    { code: 'OCC', name: 'Occitanie' },
    { code: 'PDL', name: 'Pays de la Loire' },
    { code: 'PAC', name: 'Provence-Alpes-Côte d\'Azur' },
  ],
  AE: [
    { code: 'AZ', name: 'Abu Dhabi' },
    { code: 'AJ', name: 'Ajman' },
    { code: 'DU', name: 'Dubai' },
    { code: 'FU', name: 'Fujairah' },
    { code: 'RK', name: 'Ras Al Khaimah' },
    { code: 'SH', name: 'Sharjah' },
    { code: 'UQ', name: 'Umm Al Quwain' },
  ],
  SA: [
    { code: '01', name: 'Ar Riyāḍ' },
    { code: '02', name: 'Makkah' },
    { code: '03', name: 'Madīnah' },
    { code: '04', name: 'Ash Sharqīyah' },
    { code: '05', name: 'Al Qaşīm' },
    { code: '06', name: 'Ḥā\'il' },
    { code: '07', name: 'Tabūk' },
    { code: '08', name: 'Al Ḥudūd ash Shamālīyah' },
    { code: '09', name: 'Jīzān' },
    { code: '10', name: 'Najrān' },
    { code: '11', name: 'Al Bāḥah' },
    { code: '12', name: 'Al Jawf' },
    { code: '14', name: 'ʿAsīr' },
  ],
};

export interface CityItem {
  code: string;
  name: string;
}

/** Cities by "countryCode:stateCode" - static, for cascading dropdown */
export const GEO_CITIES_BY_COUNTRY_STATE: Record<string, CityItem[]> = {
  'BD:DHA': [
    { code: 'DHA', name: 'Dhaka' },
    { code: 'GZP', name: 'Gazipur' },
    { code: 'NAR', name: 'Narayanganj' },
    { code: 'TAN', name: 'Tangail' },
    { code: 'MAN', name: 'Manikganj' },
    { code: 'MUN', name: 'Munshiganj' },
    { code: 'RAJ', name: 'Rajbari' },
    { code: 'FAR', name: 'Faridpur' },
    { code: 'GOP', name: 'Gopalganj' },
    { code: 'KIS', name: 'Kishoreganj' },
    { code: 'MAD', name: 'Madaripur' },
    { code: 'SHI', name: 'Shariatpur' },
    { code: 'NET', name: 'Narsingdi' },
  ],
  'BD:CHI': [
    { code: 'CHI', name: 'Chattogram' },
    { code: 'COX', name: 'Cox\'s Bazar' },
    { code: 'RAN', name: 'Rangamati' },
    { code: 'BAN', name: 'Bandarban' },
    { code: 'KHA', name: 'Khagrachhari' },
    { code: 'FEN', name: 'Feni' },
    { code: 'NOA', name: 'Noakhali' },
    { code: 'LAK', name: 'Lakshmipur' },
    { code: 'CHH', name: 'Chandpur' },
    { code: 'COB', name: 'Comilla' },
    { code: 'BRA', name: 'Brahmanbaria' },
  ],
  'BD:SYL': [
    { code: 'SYL', name: 'Sylhet' },
    { code: 'HAB', name: 'Habiganj' },
    { code: 'MAU', name: 'Moulvibazar' },
    { code: 'SUN', name: 'Sunamganj' },
  ],
  'BD:KHU': [
    { code: 'KHU', name: 'Khulna' },
    { code: 'BAG', name: 'Bagerhat' },
    { code: 'SAT', name: 'Satkhira' },
    { code: 'JES', name: 'Jessore' },
    { code: 'JHE', name: 'Jhenaidah' },
    { code: 'MAG', name: 'Magura' },
    { code: 'NAR', name: 'Narail' },
  ],
  'BD:RAJ': [
    { code: 'RAJ', name: 'Rajshahi' },
    { code: 'BOG', name: 'Bogura' },
    { code: 'JOY', name: 'Joypurhat' },
    { code: 'NAO', name: 'Naogaon' },
    { code: 'NAT', name: 'Natore' },
    { code: 'PAB', name: 'Pabna' },
    { code: 'SIR', name: 'Sirajganj' },
  ],
  'BD:RAN': [
    { code: 'RAN', name: 'Rangpur' },
    { code: 'DIN', name: 'Dinajpur' },
    { code: 'GAIB', name: 'Gaibandha' },
    { code: 'KUR', name: 'Kurigram' },
    { code: 'LAL', name: 'Lalmonirhat' },
    { code: 'NIL', name: 'Nilphamari' },
    { code: 'PAN', name: 'Panchagarh' },
    { code: 'THA', name: 'Thakurgaon' },
  ],
  'BD:BAR': [
    { code: 'BAR', name: 'Barishal' },
    { code: 'BHO', name: 'Bhola' },
    { code: 'BARJ', name: 'Barguna' },
    { code: 'PAT', name: 'Patuakhali' },
    { code: 'PIR', name: 'Pirojpur' },
    { code: 'JHA', name: 'Jhalokati' },
  ],
  'BD:MYM': [
    { code: 'MYM', name: 'Mymensingh' },
    { code: 'JAM', name: 'Jamalpur' },
    { code: 'NET', name: 'Netrokona' },
    { code: 'SHER', name: 'Sherpur' },
  ],
  'US:CA': [
    { code: 'LA', name: 'Los Angeles' },
    { code: 'SF', name: 'San Francisco' },
    { code: 'SD', name: 'San Diego' },
    { code: 'SJ', name: 'San Jose' },
    { code: 'OAK', name: 'Oakland' },
    { code: 'SAC', name: 'Sacramento' },
    { code: 'FRES', name: 'Fresno' },
    { code: 'LONG', name: 'Long Beach' },
  ],
  'US:NY': [
    { code: 'NYC', name: 'New York City' },
    { code: 'BUF', name: 'Buffalo' },
    { code: 'ROCH', name: 'Rochester' },
    { code: 'ALB', name: 'Albany' },
    { code: 'SYR', name: 'Syracuse' },
  ],
  'US:TX': [
    { code: 'HOU', name: 'Houston' },
    { code: 'DAL', name: 'Dallas' },
    { code: 'SAT', name: 'San Antonio' },
    { code: 'AUS', name: 'Austin' },
    { code: 'FTW', name: 'Fort Worth' },
  ],
  'IN:WB': [
    { code: 'KOL', name: 'Kolkata' },
    { code: 'HOW', name: 'Howrah' },
    { code: 'DUR', name: 'Durgapur' },
    { code: 'SIL', name: 'Siliguri' },
    { code: 'ASA', name: 'Asansol' },
  ],
  'IN:MH': [
    { code: 'MUM', name: 'Mumbai' },
    { code: 'PUN', name: 'Pune' },
    { code: 'NAG', name: 'Nagpur' },
    { code: 'THA', name: 'Thane' },
    { code: 'NAS', name: 'Nashik' },
  ],
  'IN:KA': [
    { code: 'BAN', name: 'Bangalore' },
    { code: 'MYS', name: 'Mysore' },
    { code: 'HUB', name: 'Hubli' },
    { code: 'MAN', name: 'Mangalore' },
  ],
  'GB:ENG': [
    { code: 'LON', name: 'London' },
    { code: 'BIR', name: 'Birmingham' },
    { code: 'LEE', name: 'Leeds' },
    { code: 'MAN', name: 'Manchester' },
    { code: 'LIV', name: 'Liverpool' },
    { code: 'BRI', name: 'Bristol' },
    { code: 'SHE', name: 'Sheffield' },
  ],
  'CA:ON': [
    { code: 'TOR', name: 'Toronto' },
    { code: 'OTT', name: 'Ottawa' },
    { code: 'MIS', name: 'Mississauga' },
    { code: 'HAM', name: 'Hamilton' },
    { code: 'LON', name: 'London' },
  ],
  'AU:NSW': [
    { code: 'SYD', name: 'Sydney' },
    { code: 'NEW', name: 'Newcastle' },
    { code: 'WOL', name: 'Wollongong' },
  ],
};
