ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
  ALTER TYPE "ProducerOrgStaffStatus" ADD VALUE IF NOT EXISTS 'DISABLED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
