import { PrismaClient } from "@prisma/client";

/**
 * Global country seed — idempotent via upsert by `code` (ISO 3166-1 alpha-2).
 *
 * To add a new country, simply append an entry to the `countries` array and
 * re-run `npm run seed`. The seeder will upsert by code, so existing data is
 * updated and new records are inserted.
 *
 * Bangladesh is pre-configured as the default & supported country (sortOrder: 1).
 * Admin panel can later manage isActive, isSupported, isDefault, paymentEnabled,
 * contentEnabled, and supportEnabled per country.
 */

interface CountrySeed {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  iso3?: string;
  phoneCode?: string;
  currencyCode?: string;
  currencySymbol?: string;
  flagEmoji?: string;
  isActive: boolean;
  isSupported: boolean;
  isDefault: boolean;
  sortOrder: number;
  paymentEnabled: boolean;
  contentEnabled: boolean;
  supportEnabled: boolean;
}

const countries: CountrySeed[] = [
  // ── Default / Supported ────────────────────────────────────────────────
  {
    code: "BD",
    name: "Bangladesh",
    iso3: "BGD",
    phoneCode: "+880",
    currencyCode: "BDT",
    currencySymbol: "\u09F3",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDE9",
    isActive: true,
    isSupported: true,
    isDefault: true,
    sortOrder: 1,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: true,
  },

  // ── Supported (non-default) ────────────────────────────────────────────
  {
    code: "IN",
    name: "India",
    iso3: "IND",
    phoneCode: "+91",
    currencyCode: "INR",
    currencySymbol: "\u20B9",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF3",
    isActive: true,
    isSupported: true,
    isDefault: false,
    sortOrder: 10,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: true,
  },
  {
    code: "US",
    name: "United States",
    iso3: "USA",
    phoneCode: "+1",
    currencyCode: "USD",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDFA\uD83C\uDDF8",
    isActive: true,
    isSupported: true,
    isDefault: false,
    sortOrder: 10,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: true,
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    iso3: "ARE",
    phoneCode: "+971",
    currencyCode: "AED",
    currencySymbol: "\u062F.\u0625",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDEA",
    isActive: true,
    isSupported: true,
    isDefault: false,
    sortOrder: 10,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: true,
  },

  // ── Active (non-default, non-supported) ─────────────────────────────────
  {
    code: "AF",
    name: "Afghanistan",
    iso3: "AFG",
    phoneCode: "+93",
    currencyCode: "AFN",
    currencySymbol: "\u060B",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDEB",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "AL",
    name: "Albania",
    iso3: "ALB",
    phoneCode: "+355",
    currencyCode: "ALL",
    currencySymbol: "L",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF1",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "DZ",
    name: "Algeria",
    iso3: "DZA",
    phoneCode: "+213",
    currencyCode: "DZD",
    currencySymbol: "\u062F.\u062C",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDFF",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "AR",
    name: "Argentina",
    iso3: "ARG",
    phoneCode: "+54",
    currencyCode: "ARS",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "AM",
    name: "Armenia",
    iso3: "ARM",
    phoneCode: "+374",
    currencyCode: "AMD",
    currencySymbol: "\u058F",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF2",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "AU",
    name: "Australia",
    iso3: "AUS",
    phoneCode: "+61",
    currencyCode: "AUD",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDFA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "AT",
    name: "Austria",
    iso3: "AUT",
    phoneCode: "+43",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF9",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    iso3: "AZE",
    phoneCode: "+994",
    currencyCode: "AZN",
    currencySymbol: "\u20BC",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDFF",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "BH",
    name: "Bahrain",
    iso3: "BHR",
    phoneCode: "+973",
    currencyCode: "BHD",
    currencySymbol: "\u062F.\u0628",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDED",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "BE",
    name: "Belgium",
    iso3: "BEL",
    phoneCode: "+32",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDEA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "BR",
    name: "Brazil",
    iso3: "BRA",
    phoneCode: "+55",
    currencyCode: "BRL",
    currencySymbol: "R$",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "BN",
    name: "Brunei",
    iso3: "BRN",
    phoneCode: "+673",
    currencyCode: "BND",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF3",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "KH",
    name: "Cambodia",
    iso3: "KHM",
    phoneCode: "+855",
    currencyCode: "KHR",
    currencySymbol: "\u17DB",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDED",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "CA",
    name: "Canada",
    iso3: "CAN",
    phoneCode: "+1",
    currencyCode: "CAD",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDE6",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "CN",
    name: "China",
    iso3: "CHN",
    phoneCode: "+86",
    currencyCode: "CNY",
    currencySymbol: "\u00A5",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDF3",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "DK",
    name: "Denmark",
    iso3: "DNK",
    phoneCode: "+45",
    currencyCode: "DKK",
    currencySymbol: "kr",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDF0",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "EG",
    name: "Egypt",
    iso3: "EGY",
    phoneCode: "+20",
    currencyCode: "EGP",
    currencySymbol: "\u00A3",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDEC",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "FI",
    name: "Finland",
    iso3: "FIN",
    phoneCode: "+358",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDEB\uD83C\uDDEE",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "FR",
    name: "France",
    iso3: "FRA",
    phoneCode: "+33",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDEB\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "DE",
    name: "Germany",
    iso3: "DEU",
    phoneCode: "+49",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDEA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "GR",
    name: "Greece",
    iso3: "GRC",
    phoneCode: "+30",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "HK",
    name: "Hong Kong",
    iso3: "HKG",
    phoneCode: "+852",
    currencyCode: "HKD",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDED\uD83C\uDDF0",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "IS",
    name: "Iceland",
    iso3: "ISL",
    phoneCode: "+354",
    currencyCode: "ISK",
    currencySymbol: "kr",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF8",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "ID",
    name: "Indonesia",
    iso3: "IDN",
    phoneCode: "+62",
    currencyCode: "IDR",
    currencySymbol: "Rp",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDE9",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "IR",
    name: "Iran",
    iso3: "IRN",
    phoneCode: "+98",
    currencyCode: "IRR",
    currencySymbol: "\uFDFC",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "IQ",
    name: "Iraq",
    iso3: "IRQ",
    phoneCode: "+964",
    currencyCode: "IQD",
    currencySymbol: "\u062F.\u0639",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF6",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "IE",
    name: "Ireland",
    iso3: "IRL",
    phoneCode: "+353",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDEA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "IT",
    name: "Italy",
    iso3: "ITA",
    phoneCode: "+39",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF9",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "JP",
    name: "Japan",
    iso3: "JPN",
    phoneCode: "+81",
    currencyCode: "JPY",
    currencySymbol: "\u00A5",
    flagEmoji: "\uD83C\uDDEF\uD83C\uDDF5",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "JO",
    name: "Jordan",
    iso3: "JOR",
    phoneCode: "+962",
    currencyCode: "JOD",
    currencySymbol: "\u062F.\u0623",
    flagEmoji: "\uD83C\uDDEF\uD83C\uDDF4",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "KE",
    name: "Kenya",
    iso3: "KEN",
    phoneCode: "+254",
    currencyCode: "KES",
    currencySymbol: "KSh",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDEA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "KW",
    name: "Kuwait",
    iso3: "KWT",
    phoneCode: "+965",
    currencyCode: "KWD",
    currencySymbol: "\u062F.\u0643",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDFC",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "MY",
    name: "Malaysia",
    iso3: "MYS",
    phoneCode: "+60",
    currencyCode: "MYR",
    currencySymbol: "RM",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFE",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "MV",
    name: "Maldives",
    iso3: "MDV",
    phoneCode: "+960",
    currencyCode: "MVR",
    currencySymbol: "MVR",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFB",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "MX",
    name: "Mexico",
    iso3: "MEX",
    phoneCode: "+52",
    currencyCode: "MXN",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFD",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "MA",
    name: "Morocco",
    iso3: "MAR",
    phoneCode: "+212",
    currencyCode: "MAD",
    currencySymbol: "\u062F.\u0645",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDE6",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "MM",
    name: "Myanmar",
    iso3: "MMR",
    phoneCode: "+95",
    currencyCode: "MMK",
    currencySymbol: "K",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF2",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "NP",
    name: "Nepal",
    iso3: "NPL",
    phoneCode: "+977",
    currencyCode: "NPR",
    currencySymbol: "\u0930\u0942",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF5",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "NL",
    name: "Netherlands",
    iso3: "NLD",
    phoneCode: "+31",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF1",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "NZ",
    name: "New Zealand",
    iso3: "NZL",
    phoneCode: "+64",
    currencyCode: "NZD",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDFF",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "NG",
    name: "Nigeria",
    iso3: "NGA",
    phoneCode: "+234",
    currencyCode: "NGN",
    currencySymbol: "\u20A6",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDEC",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "NO",
    name: "Norway",
    iso3: "NOR",
    phoneCode: "+47",
    currencyCode: "NOK",
    currencySymbol: "kr",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF4",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "OM",
    name: "Oman",
    iso3: "OMN",
    phoneCode: "+968",
    currencyCode: "OMR",
    currencySymbol: "\u0631.\u0639.",
    flagEmoji: "\uD83C\uDDF4\uD83C\uDDF2",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "PK",
    name: "Pakistan",
    iso3: "PAK",
    phoneCode: "+92",
    currencyCode: "PKR",
    currencySymbol: "\u20A8",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF0",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "PH",
    name: "Philippines",
    iso3: "PHL",
    phoneCode: "+63",
    currencyCode: "PHP",
    currencySymbol: "\u20B1",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDED",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "PL",
    name: "Poland",
    iso3: "POL",
    phoneCode: "+48",
    currencyCode: "PLN",
    currencySymbol: "z\u0142",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF1",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "PT",
    name: "Portugal",
    iso3: "PRT",
    phoneCode: "+351",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF9",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "QA",
    name: "Qatar",
    iso3: "QAT",
    phoneCode: "+974",
    currencyCode: "QAR",
    currencySymbol: "\u0631.\u0642",
    flagEmoji: "\uD83C\uDDF6\uD83C\uDDE6",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "RU",
    name: "Russia",
    iso3: "RUS",
    phoneCode: "+7",
    currencyCode: "RUB",
    currencySymbol: "\u20BD",
    flagEmoji: "\uD83C\uDDF7\uD83C\uDDFA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    iso3: "SAU",
    phoneCode: "+966",
    currencyCode: "SAR",
    currencySymbol: "\u0631.\u0633",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDE6",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "SG",
    name: "Singapore",
    iso3: "SGP",
    phoneCode: "+65",
    currencyCode: "SGD",
    currencySymbol: "$",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDEC",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "ZA",
    name: "South Africa",
    iso3: "ZAF",
    phoneCode: "+27",
    currencyCode: "ZAR",
    currencySymbol: "R",
    flagEmoji: "\uD83C\uDDFF\uD83C\uDDE6",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "KR",
    name: "South Korea",
    iso3: "KOR",
    phoneCode: "+82",
    currencyCode: "KRW",
    currencySymbol: "\u20A9",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "ES",
    name: "Spain",
    iso3: "ESP",
    phoneCode: "+34",
    currencyCode: "EUR",
    currencySymbol: "\u20AC",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDF8",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "LK",
    name: "Sri Lanka",
    iso3: "LKA",
    phoneCode: "+94",
    currencyCode: "LKR",
    currencySymbol: "Rs",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDF0",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "SE",
    name: "Sweden",
    iso3: "SWE",
    phoneCode: "+46",
    currencyCode: "SEK",
    currencySymbol: "kr",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDEA",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "CH",
    name: "Switzerland",
    iso3: "CHE",
    phoneCode: "+41",
    currencyCode: "CHF",
    currencySymbol: "CHF",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDED",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "TW",
    name: "Taiwan",
    iso3: "TWN",
    phoneCode: "+886",
    currencyCode: "TWD",
    currencySymbol: "NT$",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDFC",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "TH",
    name: "Thailand",
    iso3: "THA",
    phoneCode: "+66",
    currencyCode: "THB",
    currencySymbol: "\u0E3F",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDED",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "TR",
    name: "Turkey",
    iso3: "TUR",
    phoneCode: "+90",
    currencyCode: "TRY",
    currencySymbol: "\u20BA",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "GB",
    name: "United Kingdom",
    iso3: "GBR",
    phoneCode: "+44",
    currencyCode: "GBP",
    currencySymbol: "\u00A3",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDE7",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: true,
    contentEnabled: true,
    supportEnabled: false,
  },
  {
    code: "VN",
    name: "Vietnam",
    iso3: "VNM",
    phoneCode: "+84",
    currencyCode: "VND",
    currencySymbol: "\u20AB",
    flagEmoji: "\uD83C\uDDFB\uD83C\uDDF3",
    isActive: true,
    isSupported: false,
    isDefault: false,
    sortOrder: 100,
    paymentEnabled: false,
    contentEnabled: true,
    supportEnabled: false,
  },
];

export default async function seedCountries(prisma: PrismaClient) {
  let created = 0;
  let updated = 0;

  for (const c of countries) {
    const record = await prisma.country.upsert({
      where: { code: c.code },
      update: {
        name: c.name,
        iso3: c.iso3,
        phoneCode: c.phoneCode,
        currencyCode: c.currencyCode,
        currencySymbol: c.currencySymbol,
        flagEmoji: c.flagEmoji,
        isActive: c.isActive,
        isSupported: c.isSupported,
        isDefault: c.isDefault,
        sortOrder: c.sortOrder,
        paymentEnabled: c.paymentEnabled,
        contentEnabled: c.contentEnabled,
        supportEnabled: c.supportEnabled,
      },
      create: {
        code: c.code,
        name: c.name,
        iso3: c.iso3,
        phoneCode: c.phoneCode,
        currencyCode: c.currencyCode,
        currencySymbol: c.currencySymbol,
        flagEmoji: c.flagEmoji,
        isActive: c.isActive,
        isSupported: c.isSupported,
        isDefault: c.isDefault,
        sortOrder: c.sortOrder,
        paymentEnabled: c.paymentEnabled,
        contentEnabled: c.contentEnabled,
        supportEnabled: c.supportEnabled,
      },
    });

    if (record.createdAt === record.updatedAt) {
      created++;
    } else {
      updated++;
    }
  }

  console.log(`\u2705 Seeded ${countries.length} countries (${created} created, ${updated} updated)`);
}
