import { PrismaClient } from "@prisma/client";

type SeedPermission = { key: string; label: string; description?: string };
type SeedRole = { key: string; label: string; scope: "ORG" | "BRANCH"; permissionKeys: string[] };

/**
 * Seeds system Roles + Permissions + RolePermission matrix.
 * Safe to run multiple times (upsert-based).
 */
export default async function seedRolesPermissions(prisma: PrismaClient) {
  const permissions: SeedPermission[] = [
    { key: "org.read", label: "Read organization" },
    { key: "org.write", label: "Manage organization" },
    { key: "pricing.central.read", label: "View central pricing & governance policy" },
    { key: "pricing.central.write", label: "Central catalog pricing (MRP/base/floor)" },
    { key: "pricing.branch.override", label: "Branch price overrides within central policy" },
    { key: "pricing.audit.view", label: "View pricing audit log" },
    { key: "pricing.retail.rule.manage", label: "Manage retail discount rules" },
    { key: "retail.discount.apply", label: "Apply retail / POS discounts" },
    { key: "retail.discount.approve", label: "Approve over-limit retail discounts" },
    { key: "pricing.campaign.manage", label: "Manage retail pricing campaigns" },
    { key: "pricing.membership.manage", label: "Manage membership pricing tiers" },
    { key: "pricing.branch.override.request", label: "Request branch price override approval" },
    { key: "pricing.branch.override.approve", label: "Approve branch price override requests" },
    { key: "pricing.approval.matrix.manage", label: "Manage pricing approval matrix" },
    { key: "pricing.emergency.override", label: "Create emergency POS price overrides" },
    { key: "pricing.analytics.view", label: "View pricing analytics" },
    { key: "pricing.bulk.import", label: "Bulk import catalog prices" },
    { key: "branches.read", label: "Read branches" },
    { key: "branches.write", label: "Manage branches" },

    { key: "staff.read", label: "Read staff" },
    { key: "staff.write", label: "Manage staff" },

    { key: "orders.read", label: "Read orders" },
    { key: "orders.write", label: "Manage orders" },

    { key: "inventory.read", label: "Read inventory" },
    { key: "inventory.write", label: "Manage inventory" },
    { key: "inventory.batch.pricing", label: "Set batch sell price and expiry (SHOP, branch manager)" },
    { key: "inventory.adjust", label: "Adjust inventory quantities (ledger)" },
    { key: "inventory.transfer", label: "Transfer stock between locations" },
    { key: "inventory.emergency.override", label: "Emergency override for warehouse operations (owner/admin only)" },

    { key: "customers.read", label: "Read customers" },
    { key: "customers.write", label: "Manage customers" },

    { key: "reports.read", label: "Read reports" },

    { key: "settings.read", label: "Read settings" },
    { key: "settings.write", label: "Manage settings" },

    { key: "delivery.read", label: "Read delivery" },
    { key: "delivery.write", label: "Manage delivery" },
    { key: "delivery.view", label: "View delivery assignments (warehouse)" },
    { key: "delivery.assign", label: "Assign delivery runs" },
    { key: "delivery.manage", label: "Manage delivery lifecycle" },
    { key: "delivery.pod.submit", label: "Submit proof of delivery" },
    { key: "procurement.po.view", label: "View purchase orders" },
    { key: "procurement.po.manage", label: "Manage purchase orders" },
    { key: "procurement.request.view", label: "View procurement requests (warehouse replenishment)" },
    { key: "procurement.request.manage", label: "Manage procurement requests (approve, link to PO)" },
    { key: "procurement.demand.view", label: "View procurement demand lines (allocation shortage → PO)" },
    { key: "procurement.demand.manage", label: "Manage procurement demand lines (link PO, cancel)" },
    { key: "procurement.demand.link_po", label: "Link procurement demand to purchase order lines" },
    { key: "fulfillment.backorder.view", label: "View stock request backorder / procurement demand status" },
    { key: "fulfillment.backorder.process", label: "Process backorder fulfillment hooks (warehouse)" },
    { key: "warehouse.allocation.manage", label: "Allocation plans (FEFO)" },
    { key: "warehouse.pick.execute", label: "Execute pick lists" },

    { key: "warehouse.view", label: "View warehouses" },
    { key: "warehouse.manage", label: "Manage warehouse settings" },
    { key: "warehouse.staff.manage", label: "Manage warehouse staff assignments" },
    { key: "warehouse.locations.manage", label: "Link inventory locations to warehouse" },
    { key: "warehouse.dashboard.view", label: "View warehouse dashboard KPIs" },
    { key: "warehouse.operations", label: "Warehouse operations hub" },
    { key: "warehouse.pick", label: "View warehouse pick lists" },
    { key: "warehouse.qc", label: "View warehouse QC queue" },
    { key: "inventory.receive", label: "Receive stock / GRN at branch" },
    { key: "qc.view", label: "View QC inspections and quarantine queue" },
    { key: "qc.inspect", label: "Submit QC inspections" },
    { key: "qc.release", label: "Release stock from quarantine" },
    { key: "quarantine.view", label: "View quarantine holdings" },
    { key: "quarantine.manage", label: "Manage quarantine release and disposal" },
    { key: "audit.view", label: "View warehouse audit export" },
    { key: "audit.export", label: "Export warehouse audit CSV" },
    { key: "warehouse.zone.manage", label: "Manage warehouse zones and location bins" },
    { key: "recall.allocation.release", label: "Release recalled lots for supervised allocation" },

    { key: "inbound.read", label: "View inbound queue" },
    { key: "inbound.receive", label: "Receive inbound stock" },
    { key: "inbound.grn", label: "Post GRN against inbound" },

    { key: "purchase.receive", label: "Purchase receive (vendor GRN against PO)" },
    { key: "grn.view", label: "View goods receipt notes (GRN)" },
    { key: "grn.create", label: "Create draft GRNs" },
    { key: "grn.post", label: "Post GRN to inventory (receive)" },
    { key: "grn.confirm.warehouse_manager", label: "Confirm vendor GRN posting after verification (warehouse manager)" },
    { key: "grn.void", label: "Void draft GRNs" },
    { key: "batch.manage", label: "Manage lot/batch fields on GRN receive" },
    { key: "barcode.manage", label: "Manage supplier/receive barcodes on GRN" },
    { key: "distribution.view", label: "View DC distribution recommendations" },
    { key: "distribution.execute", label: "Accept or dismiss DC distribution recommendations" },
    { key: "qc.execute", label: "Execute QC inspections (same scope as qc.inspect)" },

    { key: "outbound.read", label: "View outbound queue" },
    { key: "outbound.dispatch", label: "Create and dispatch outbound" },
    { key: "outbound.pack", label: "Pack outbound" },

    { key: "dispatch.view", label: "View stock dispatches" },
    { key: "dispatch.create", label: "Create dispatches" },
    { key: "dispatch.manage", label: "Manage dispatches" },
    { key: "dispatch.receive.verify", label: "Save dispatch receive verification (draft, no stock post)" },
    { key: "dispatch.receive.confirm.branch_manager", label: "Confirm dispatch receive and post branch stock" },

    { key: "clinic.appointments.read", label: "Read appointments" },
    { key: "clinic.appointments.manage", label: "Manage appointments" },
    { key: "clinic.appointments.collect_payment", label: "Collect appointment payment" },
    { key: "clinic.appointments.apply_discount", label: "Apply discount" },
    { key: "clinic.appointments.reprint", label: "Reprint slips" },
    { key: "clinic.appointments.assign_doctor", label: "Assign doctor to appointment" },
    { key: "clinic.queue.read", label: "Read queue" },
    { key: "clinic.queue.manage", label: "Manage queue" },
    { key: "clinic.queue.screen", label: "View queue screen" },
    { key: "clinic.patients.read", label: "Read patients" },
    { key: "clinic.patients.manage", label: "Manage patients" },
    { key: "clinic.visits.read", label: "Read visits" },
    { key: "clinic.visits.manage", label: "Manage visits" },
    { key: "clinic.emr.read", label: "View EMR" },
    { key: "clinic.emr.write", label: "Write EMR" },
    { key: "clinic.prescription.read", label: "View prescriptions" },
    {
      key: "clinic.prescription.write",
      label: "Write prescriptions [RETIRED — use create/edit/finalize; not used by clinic Rx routes]",
    },
    { key: "clinic.prescription.create", label: "Create prescriptions (PRESCRIPTION_CREATE)" },
    { key: "clinic.prescription.edit", label: "Edit draft prescriptions (PRESCRIPTION_EDIT)" },
    { key: "clinic.prescription.finalize", label: "Finalize prescriptions" },
    { key: "clinic.prescription.delete", label: "Delete prescriptions (PRESCRIPTION_DELETE; reserved)" },
    { key: "clinic.settings.read", label: "View clinic settings" },
    { key: "clinic.settings.write", label: "Edit clinic settings" },
    { key: "clinic.services.manage", label: "Manage clinic services" },
    { key: "clinic.overview.read", label: "View clinic overview" },
    { key: "clinic.rooms.manage", label: "Manage clinic rooms" },
    { key: "clinic.rooms.create", label: "Create clinic rooms" },
    { key: "clinic.rooms.update", label: "Update clinic rooms" },
    { key: "clinic.rooms.assign", label: "Assign room to appointment" },
    { key: "clinic.rooms.reassign", label: "Reassign room" },
    { key: "clinic.rooms.view_schedule", label: "View room schedule board" },
    { key: "clinic.rooms.view_live", label: "View live room monitor" },
    { key: "clinic.rooms.manage_blocks", label: "Manage room blocks" },
    { key: "clinic.rooms.mark_cleaning", label: "Mark room cleaning" },
    { key: "clinic.rooms.mark_occupied", label: "Mark room occupied" },
    { key: "clinic.rooms.deactivate", label: "Deactivate clinic room" },
    { key: "clinic.rooms.view_analytics", label: "View room analytics" },
    { key: "clinic.rooms.view_audit", label: "View room audit" },
    { key: "clinic.rooms.emergency_override", label: "Emergency override room" },
    { key: "clinic.rooms.approve_changes", label: "Approve room changes" },
    { key: "clinic.staff.manage", label: "Manage clinic staff profiles" },
    { key: "clinic.schedule.manage", label: "Manage clinic schedule templates" },
    { key: "clinic.holidays.manage", label: "Manage clinic holidays" },
    { key: "clinic.emergency.manage", label: "Manage emergency slot policy" },
    { key: "clinic.fees.manage", label: "Manage clinic fees" },

    // Clinic Supply Chain (enterprise)
    { key: "clinic.supply.request.create", label: "Create supply request" },
    { key: "clinic.supply.request.submit", label: "Submit supply request" },
    { key: "clinic.supply.request.review", label: "Review supply request" },
    { key: "clinic.supply.transfer.dispatch", label: "Dispatch transfer" },
    { key: "clinic.supply.transfer.receive", label: "Receive transfer" },
    { key: "clinic.sterilization.manage", label: "Manage sterilization" },
    { key: "clinic.instrument.manage", label: "Manage instruments" },
    { key: "clinic.audit.create", label: "Create stock audit" },
    { key: "clinic.audit.approve", label: "Approve stock audit" },
    { key: "clinic.wastage.report", label: "Report wastage" },
    { key: "clinic.wastage.approve", label: "Approve wastage" },
    { key: "clinic.refill.view", label: "View refill suggestions" },
    { key: "clinic.refill.convert", label: "Convert to supply request" },
    { key: "clinic.items.read", label: "View clinical items" },
    { key: "clinic.stock.read", label: "View clinical stock" },

    // Medicine Control (CCMLPA)
    { key: "medicine.policy.read", label: "View medicine policies" },
    { key: "medicine.policy.manage", label: "Manage medicine policies" },
    { key: "medicine.dispense.request", label: "Request medicine dispense" },
    { key: "medicine.dispense.approve", label: "Approve dispense requests" },
    { key: "medicine.override.approve", label: "Approve medicine overrides (Manager/Owner)" },
    { key: "medicine.dispense.issue", label: "Issue medicine" },
    { key: "medicine.vial.open", label: "Open vial" },
    { key: "medicine.vial.activate", label: "Activate vial in injection room" },
    { key: "medicine.vial.force_open", label: "Force open vial" },
    { key: "medicine.vial.use", label: "Log vial dose use" },
    { key: "medicine.vial.return", label: "Return vial" },
    { key: "medicine.dose.record", label: "Record dose" },
    { key: "medicine.dose.read", label: "View dose records" },
    { key: "injection.token.generate", label: "Generate injection token" },
    { key: "injection.token.validate", label: "Validate injection token" },
    { key: "injection.token.list", label: "View injection token list" },
    { key: "injection.token.cancel", label: "Cancel injection token" },
    { key: "injection.token.emergency_bypass", label: "Emergency bypass injection token gate" },
    { key: "medicine.reconciliation.run", label: "Run daily reconciliation" },
    { key: "medicine.reconciliation.read", label: "Read daily reconciliation" },
    { key: "medicine.reconciliation.acknowledge", label: "Acknowledge mismatch reconciliation" },
    { key: "medicine.return.submit", label: "Submit vial return" },
    { key: "medicine.return.verify", label: "Verify vial return" },
    { key: "medicine.audit.bin.view", label: "View audit bins" },
    { key: "medicine.audit.bin.manage", label: "Manage audit bins" },
    { key: "medicine.destruction.approve", label: "Approve destruction" },

    // Producer Authentication System
    { key: "producer.org.read", label: "Read producer organization", description: "View producer organization details" },
    { key: "producer.org.write", label: "Manage producer organization", description: "Edit producer organization settings" },
    { key: "producer.kyc.submit", label: "Submit KYC", description: "Submit KYC documents for verification" },
    { key: "producer.kyc.view", label: "View KYC status", description: "Check KYC verification status" },
    { key: "producer.products.read", label: "Read products", description: "View product list and details" },
    { key: "producer.products.write", label: "Manage products", description: "Create and edit products" },
    { key: "producer.batches.read", label: "Read batches", description: "View batch list and details" },
    { key: "producer.batches.write", label: "Manage batches", description: "Create and manage production batches" },
    { key: "producer.batches.print", label: "Print batch / Mark batch as printed", description: "Record batch print events and view print count" },
    { key: "producer.codes.generate", label: "Generate QR codes", description: "Generate authenticity QR codes" },
    { key: "producer.codes.export", label: "Export codes", description: "Export generated codes" },
    { key: "producer.codes.revoke", label: "Revoke allocations", description: "Revoke issued serial allocations (owner only)" },
    { key: "producer.verification.read", label: "Read verification logs", description: "View verification history and analytics" },
    { key: "producer.analytics.read", label: "Read analytics", description: "View producer analytics and reports" },
    { key: "producer.tickets.read", label: "View support tickets", description: "View own org support tickets and messages." },
    { key: "producer.tickets.write", label: "Create and reply to tickets", description: "Create tickets, reply, close, reopen." },

    // Manager Operations (Branch Manager Control)
    { key: "manager.appointments.create", label: "Create appointments" },
    { key: "manager.appointments.assign_doctor", label: "Assign doctor" },
    { key: "manager.appointments.cancel", label: "Cancel appointments" },
    { key: "manager.appointments.reschedule", label: "Reschedule appointments" },
    { key: "manager.walkin.register", label: "Register walk-in" },
    { key: "manager.patients.create", label: "Create patients" },
    { key: "manager.patients.edit", label: "Edit patients" },
    { key: "manager.patients.view_history", label: "View patient history" },
    { key: "manager.inventory.update_stock", label: "Update stock" },
    { key: "manager.inventory.supply_request", label: "Supply request" },
    { key: "manager.inventory.purchase_request", label: "Purchase request" },
    { key: "manager.inventory.low_stock_alert", label: "Low stock alert" },
    { key: "manager.services.enable_disable", label: "Enable/disable services" },
    { key: "manager.packages.activate", label: "Activate packages" },
    { key: "manager.discount.apply", label: "Apply discount" },
    { key: "manager.pricing.view", label: "View pricing" },
    { key: "manager.staff.assign", label: "Assign staff" },
    { key: "manager.staff.duty_roster", label: "Duty roster" },
    { key: "manager.staff.leave_approve", label: "Approve leave" },
    { key: "manager.staff.performance_view", label: "View staff performance" },
    { key: "manager.billing.create_invoice", label: "Create invoice" },
    { key: "manager.billing.collect_payment", label: "Collect payment" },
    { key: "manager.billing.refund_request", label: "Refund request" },
    { key: "manager.reports.daily_revenue", label: "Daily revenue report" },
    { key: "manager.reports.doctor_performance", label: "Doctor performance report" },
    { key: "manager.reports.inventory_usage", label: "Inventory usage report" },
    { key: "manager.reports.export", label: "Export reports" },
    { key: "manager.branch.settings", label: "Branch settings" },
    { key: "manager.branch.hours", label: "Branch hours" },
    { key: "manager.branch.announcements", label: "Branch announcements" },

    // Clinic Enterprise RBAC (Branch Manager Permission Matrix)
    { key: "clinic.analytics.view", label: "View clinic analytics (today revenue / patients)" },
    { key: "clinic.stats.view", label: "View operation / service reports" },
    { key: "clinic.doctors.view", label: "View branch doctor list" },
    { key: "clinic.doctors.assign", label: "Assign doctor to branch" },
    { key: "clinic.doctors.invite", label: "Invite doctor (via approval)" },
    { key: "clinic.doctors.manage_schedule", label: "Manage doctor schedule" },
    { key: "clinic.doctors.manage_services", label: "Manage doctor service mapping" },
    { key: "clinic.doctors.manage_packages", label: "Manage doctor package mapping" },
    { key: "clinic.doctors.manage_leave", label: "Manage doctor leave and availability" },
    { key: "clinic.doctors.manage_credentials", label: "Manage doctor credentials review" },
    { key: "clinic.doctors.propose_fee", label: "Propose doctor fee change" },
    { key: "clinic.doctors.request_activation", label: "Request doctor activation" },
    { key: "clinic.doctors.view_performance", label: "View doctor performance and earnings" },
    { key: "clinic.doctors.view_audit", label: "View doctor audit logs" },
    { key: "clinic.doctors.approve_requests", label: "Approve doctor-related requests" },
    { key: "clinic.doctors.create", label: "Create doctor (Owner only)" },
    { key: "clinic.doctors.delete", label: "Delete doctor (Owner only)" },
    { key: "clinic.packages.read", label: "View packages" },
    { key: "clinic.packages.write", label: "Create / edit packages" },
    { key: "clinic.packages.delete", label: "Delete package" },
    { key: "clinic.packages.deactivate", label: "Deactivate package" },
    { key: "clinic.packages.items.manage", label: "Add/remove items in package" },
    { key: "clinic.packages.high_discount", label: "Apply high discount (Owner approval)" },
    { key: "clinic.packages.global_create", label: "Create global package (Owner only)" },
    { key: "clinic.catalog.view", label: "View catalog" },
    { key: "clinic.catalog.search", label: "Search catalog" },
    { key: "clinic.catalog.branch_add", label: "Add catalog item to branch" },
    { key: "clinic.catalog.branch_remove", label: "Remove catalog item from branch" },
    { key: "catalog.master.create", label: "Create master catalog item (Owner only)" },
    { key: "catalog.master.edit", label: "Edit master catalog (Owner only)" },
    { key: "catalog.master.delete", label: "Delete master catalog (Owner only)" },
    { key: "clinic.inventory.issue", label: "Stock issue" },
    { key: "clinic.inventory.return", label: "Stock return" },
    { key: "inventory.purchase.approve", label: "Approve purchase (Owner approval)" },
    { key: "clinic.audit.view", label: "View audit reports" },
    { key: "clinic.rooms.view", label: "View rooms (read-only)" },
    { key: "clinic.billing.view", label: "View billing" },
    { key: "clinic.billing.adjust", label: "Adjust bill" },
    { key: "clinic.reports.branch_analytics", label: "Branch-level analytics" },
    { key: "clinic.reports.global_analytics", label: "Cross-branch analytics (Owner only)" },
    { key: "clinic.settings.global", label: "Global clinic settings (Owner only)" },
    { key: "clinic.staff.delete", label: "Delete staff (Owner only)" },
    { key: "clinic.services.global_create", label: "Create global service (Owner only)" },

    // Enterprise Surgery Module
    { key: "clinic.surgery.read", label: "View surgery list and details" },
    { key: "clinic.surgery.create", label: "Create surgery cases" },
    { key: "clinic.surgery.manage", label: "Update status, assign staff" },
    { key: "clinic.surgery.notes.write", label: "Pre-op/post-op/operative notes" },
    { key: "clinic.surgery.billing", label: "Estimate, finalize bill" },
    { key: "clinic.surgery.payout", label: "Generate/approve payouts" },
    { key: "clinic.surgery.reports", label: "View surgery reports" },

    // AI Intelligence Phase 4 (inventory)
    { key: "inventory.ai.forecast.read", label: "AI demand forecast" },
    { key: "inventory.ai.replenishment.manage", label: "AI replenishment suggestions" },
    { key: "inventory.ai.procurement.read", label: "AI procurement recommendations" },
    { key: "inventory.ai.control_tower.read", label: "Inventory control tower" },
    { key: "inventory.executive_tower.read", label: "Executive network command (Wave-5)" },
    { key: "inventory.executive_tower.manage", label: "Executive tower actions" },
    { key: "inventory.financial.read", label: "Financial intelligence & CTS" },
    { key: "inventory.slo.read", label: "Service level (SLO) dashboard" },
    { key: "operations.command_center.read", label: "Exception command center" },
    { key: "operations.command_center.manage", label: "Manage exception queue" },
    { key: "admin.vendor.analytics.read", label: "Vendor analytics (admin)" },
    { key: "location.master.read", label: "Read centralized location master" },
    { key: "location.master.manage", label: "Manage centralized location master" },
    { key: "location.coverage.read", label: "Read location coverage assignments" },
    { key: "location.coverage.manage", label: "Manage location coverage assignments" },
    { key: "location.migration.manage", label: "Run location migration/backfill operations" },
  ];

  const roles: SeedRole[] = [
    {
      key: "OWNER",
      label: "Owner",
      scope: "ORG",
      permissionKeys: permissions.map((p) => p.key),
    },
    {
      key: "ORG_ADMIN",
      label: "Org Admin",
      scope: "ORG",
      permissionKeys: [
        "org.read","org.write",
        "pricing.central.read","pricing.central.write","pricing.branch.override","pricing.audit.view","pricing.retail.rule.manage","retail.discount.apply","retail.discount.approve",
        "pricing.campaign.manage","pricing.membership.manage","pricing.branch.override.request","pricing.branch.override.approve",
        "pricing.approval.matrix.manage","pricing.emergency.override","pricing.analytics.view","pricing.bulk.import",
        "branches.read","branches.write",
        "staff.read","staff.write",
        "orders.read","orders.write",
        "inventory.read","inventory.write",
        "customers.read","customers.write",
        "reports.read",
        "settings.read","settings.write",
        "warehouse.view","warehouse.manage","warehouse.staff.manage","warehouse.locations.manage","warehouse.dashboard.view",
        "qc.view","qc.inspect","qc.release","quarantine.view","quarantine.manage","audit.view","audit.export","warehouse.zone.manage","recall.allocation.release",
        "inbound.read","inbound.receive","inbound.grn",
        "purchase.receive","grn.view","grn.create","grn.post","grn.confirm.warehouse_manager","grn.void","batch.manage","barcode.manage","distribution.view","distribution.execute","qc.execute",
        "dispatch.receive.verify","dispatch.receive.confirm.branch_manager",
        "outbound.read","outbound.dispatch","outbound.pack",
        "delivery.read","delivery.write","delivery.view","delivery.assign","delivery.manage",
        "delivery.pod.submit",
        "procurement.po.view","procurement.po.manage",
        "procurement.request.view","procurement.request.manage",
        "procurement.demand.view","procurement.demand.manage","procurement.demand.link_po",
        "fulfillment.backorder.view","fulfillment.backorder.process",
        "warehouse.allocation.manage","warehouse.pick.execute",
        "dispatch.view","dispatch.create","dispatch.manage",
        "inventory.ai.forecast.read","inventory.ai.replenishment.manage","inventory.ai.procurement.read","inventory.ai.control_tower.read",
        "inventory.executive_tower.read","inventory.executive_tower.manage",
        "inventory.financial.read","inventory.slo.read","operations.command_center.read","operations.command_center.manage",
        "admin.vendor.analytics.read",
        "location.master.read","location.master.manage","location.coverage.read","location.coverage.manage","location.migration.manage",
      ],
    },
    {
      key: "BRANCH_MANAGER",
      label: "Branch Manager",
      scope: "BRANCH",
      permissionKeys: [
        "branches.read",
        "staff.read","staff.write",
        "orders.read","orders.write",
        "inventory.read","inventory.write","inventory.batch.pricing",
        "customers.read","customers.write",
        "reports.read",
        "retail.discount.apply","retail.discount.approve",
        "pricing.branch.override.request",
        "clinic.settings.read","clinic.settings.write",
        "clinic.services.manage","clinic.overview.read",
        "clinic.rooms.manage","clinic.rooms.view",
        "clinic.rooms.update","clinic.rooms.assign","clinic.rooms.reassign",
        "clinic.rooms.view_schedule","clinic.rooms.view_live",
        "clinic.rooms.manage_blocks","clinic.rooms.mark_cleaning","clinic.rooms.mark_occupied",
        "clinic.rooms.view_analytics","clinic.rooms.view_audit","clinic.rooms.emergency_override",
        "clinic.staff.manage",
        "clinic.schedule.manage",
        "clinic.holidays.manage",
        "clinic.emergency.manage",
        "clinic.fees.manage",
        "manager.appointments.create","manager.appointments.assign_doctor","manager.appointments.cancel","manager.appointments.reschedule","manager.walkin.register",
        "manager.patients.create","manager.patients.edit","manager.patients.view_history",
        "manager.inventory.update_stock","manager.inventory.supply_request","manager.inventory.purchase_request","manager.inventory.low_stock_alert",
        "manager.services.enable_disable","manager.packages.activate","manager.discount.apply","manager.pricing.view",
        "manager.staff.assign","manager.staff.duty_roster","manager.staff.leave_approve","manager.staff.performance_view",
        "manager.billing.create_invoice","manager.billing.collect_payment","manager.billing.refund_request",
        "manager.reports.daily_revenue","manager.reports.doctor_performance","manager.reports.inventory_usage","manager.reports.export",
        "manager.branch.settings","manager.branch.hours","manager.branch.announcements",
        "clinic.analytics.view","clinic.stats.view",
        "clinic.doctors.view","clinic.doctors.assign",
        "clinic.doctors.invite","clinic.doctors.manage_schedule","clinic.doctors.manage_services","clinic.doctors.manage_packages",
        "clinic.doctors.manage_leave","clinic.doctors.manage_credentials","clinic.doctors.propose_fee","clinic.doctors.request_activation",
        "clinic.doctors.view_performance","clinic.doctors.view_audit","clinic.doctors.approve_requests",
        "clinic.packages.read","clinic.packages.write","clinic.packages.delete","clinic.packages.deactivate","clinic.packages.items.manage",
        "clinic.catalog.view","clinic.catalog.search","clinic.catalog.branch_add","clinic.catalog.branch_remove",
        "clinic.inventory.issue","clinic.inventory.return",
        "clinic.audit.view","clinic.billing.view","clinic.billing.adjust",
        "medicine.policy.read","medicine.policy.manage",
        "medicine.dispense.request","medicine.dispense.approve","medicine.override.approve","medicine.dispense.issue",
        "medicine.vial.open","medicine.vial.activate","medicine.vial.force_open","medicine.vial.use","medicine.vial.return",
        "medicine.dose.record","medicine.dose.read",
        "injection.token.generate","injection.token.validate","injection.token.list","injection.token.cancel","injection.token.emergency_bypass",
        "medicine.reconciliation.run","medicine.reconciliation.read","medicine.reconciliation.acknowledge",
        "medicine.return.submit","medicine.return.verify","medicine.audit.bin.view","medicine.audit.bin.manage","medicine.destruction.approve",
        "clinic.reports.branch_analytics",
        "clinic.surgery.read","clinic.surgery.create","clinic.surgery.manage","clinic.surgery.notes.write","clinic.surgery.billing","clinic.surgery.payout","clinic.surgery.reports",
        "inventory.ai.forecast.read","inventory.ai.replenishment.manage","inventory.ai.procurement.read","inventory.ai.control_tower.read",
        "inventory.executive_tower.read","inventory.executive_tower.manage",
        "inventory.financial.read","inventory.slo.read","operations.command_center.read","operations.command_center.manage",
        "location.master.read","location.coverage.read","location.coverage.manage",
      ],
    },
    {
      key: "SELLER",
      label: "Seller",
      scope: "BRANCH",
      permissionKeys: ["orders.read","orders.write","customers.read","inventory.read","retail.discount.apply"],
    },
    {
      key: "BRANCH_STAFF",
      label: "Branch Staff",
      scope: "BRANCH",
      permissionKeys: ["orders.read","orders.write","inventory.read","customers.read","branches.read","inventory.ai.forecast.read","inventory.ai.replenishment.manage"],
    },
    {
      key: "DELIVERY_MANAGER",
      label: "Delivery Manager",
      scope: "BRANCH",
      permissionKeys: [
        "orders.read",
        "delivery.read",
        "delivery.write",
        "delivery.view",
        "delivery.assign",
        "delivery.manage",
        "warehouse.view",
        "warehouse.dashboard.view",
      ],
    },
    {
      key: "DELIVERY_STAFF",
      label: "Delivery Staff",
      scope: "BRANCH",
      permissionKeys: [
        "orders.read",
        "delivery.read",
        "delivery.view",
        "delivery.pod.submit",
        "warehouse.view",
        "warehouse.dashboard.view",
      ],
    },
    {
      key: "WAREHOUSE_MANAGER",
      label: "Warehouse Manager",
      scope: "BRANCH",
      permissionKeys: [
        "inventory.read",
        "inventory.receive",
        "inventory.write",
        "warehouse.view",
        "warehouse.manage",
        "warehouse.staff.manage",
        "warehouse.locations.manage",
        "warehouse.dashboard.view",
        "dispatch.view",
        "dispatch.create",
        "dispatch.manage",
        "delivery.read",
        "delivery.write",
        "delivery.view",
        "delivery.assign",
        "delivery.manage",
        "inbound.read",
        "inbound.receive",
        "inbound.grn",
        "outbound.read",
        "outbound.dispatch",
        "outbound.pack",
        "reports.read",
        "qc.view",
        "qc.inspect",
        "qc.release",
        "quarantine.view",
        "quarantine.manage",
        "audit.view",
        "audit.export",
        "warehouse.zone.manage",
        "recall.allocation.release",
        "warehouse.operations",
        "warehouse.pick",
        "warehouse.qc",
        "procurement.po.view",
        "procurement.demand.view",
        "fulfillment.backorder.view",
        "fulfillment.backorder.process",
        "purchase.receive",
        "grn.view",
        "grn.create",
        "grn.post",
        "grn.confirm.warehouse_manager",
        "grn.void",
        "batch.manage",
        "barcode.manage",
        "dispatch.receive.verify",
        "dispatch.receive.confirm.branch_manager",
      ],
    },
    {
      key: "RECEIVING_STAFF",
      label: "Receiving Staff",
      scope: "BRANCH",
      permissionKeys: [
        "inventory.read",
        "inventory.receive",
        "warehouse.view",
        "warehouse.dashboard.view",
        "dispatch.view",
        "inbound.read",
        "inbound.receive",
        "inbound.grn",
        "qc.view",
        "qc.inspect",
        "warehouse.operations",
        "warehouse.qc",
        "procurement.po.view",
        "purchase.receive",
        "grn.view",
        "grn.create",
        "grn.post",
        "grn.void",
        "batch.manage",
        "barcode.manage",
        "dispatch.receive.verify",
      ],
    },
    {
      key: "DISPATCH_STAFF",
      label: "Dispatch Staff",
      scope: "BRANCH",
      permissionKeys: [
        "inventory.read",
        "warehouse.view",
        "warehouse.dashboard.view",
        "dispatch.view",
        "dispatch.create",
        "dispatch.manage",
        "delivery.read",
        "delivery.view",
        "delivery.assign",
        "delivery.pod.submit",
        "warehouse.pick.execute",
        "outbound.read",
        "outbound.dispatch",
        "warehouse.operations",
        "warehouse.pick",
      ],
    },
    {
      key: "DOCTOR",
      label: "Doctor (branch member)",
      scope: "BRANCH",
      permissionKeys: [
        "clinic.appointments.read",
        "clinic.appointments.manage",
        "clinic.patients.read",
        "clinic.patients.manage",
        "clinic.visits.read",
        "clinic.visits.manage",
        "clinic.settings.read",
        "clinic.overview.read",
        "clinic.services.manage",
        "clinic.queue.manage",
        "clinic.queue.screen",
        "clinic.emr.read",
        "clinic.emr.write",
        "clinic.prescription.read",
        "clinic.prescription.create",
        "clinic.prescription.edit",
        "clinic.prescription.finalize",
        "medicine.policy.read",
        "medicine.dispense.request",
        "medicine.dispense.approve",
        "medicine.override.approve",
        "medicine.dispense.issue",
        "medicine.vial.open",
        "medicine.vial.activate",
        "medicine.vial.force_open",
        "medicine.vial.use",
        "medicine.vial.return",
        "medicine.dose.record",
        "medicine.dose.read",
        "injection.token.generate",
        "injection.token.validate",
        "injection.token.list",
        "injection.token.cancel",
        "medicine.reconciliation.run",
        "medicine.reconciliation.read",
        "medicine.reconciliation.acknowledge",
        "medicine.return.submit",
        "medicine.return.verify",
        "medicine.audit.bin.view",
        "clinic.rooms.view",
        "clinic.analytics.view",
        "clinic.surgery.read",
        "clinic.surgery.create",
        "clinic.surgery.manage",
        "clinic.surgery.notes.write",
        "location.master.read",
        "location.coverage.read",
        "location.coverage.manage",
      ],
    },
    {
      key: "PHARMACIST",
      label: "Pharmacist",
      scope: "BRANCH",
      permissionKeys: [
        "clinic.prescription.read",
        "clinic.catalog.view",
        "clinic.catalog.search",
        "inventory.read",
        "inventory.receive",
        "medicine.policy.read",
        "medicine.dispense.request",
        "medicine.dispense.approve",
        "medicine.dispense.issue",
        "medicine.vial.open",
        "medicine.vial.use",
        "medicine.vial.return",
        "medicine.dose.record",
        "medicine.dose.read",
        "injection.token.validate",
        "injection.token.list",
      ],
    },
    {
      key: "GROOMING_STAFF",
      label: "Grooming Staff",
      scope: "BRANCH",
      permissionKeys: ["orders.read", "customers.read", "inventory.read", "branches.read"],
    },
    {
      key: "BOARDING_STAFF",
      label: "Boarding / Daycare Staff",
      scope: "BRANCH",
      permissionKeys: ["orders.read", "customers.read", "inventory.read", "branches.read"],
    },
    {
      key: "TRAINING_STAFF",
      label: "Training Staff",
      scope: "BRANCH",
      permissionKeys: ["orders.read", "customers.read", "branches.read"],
    },
    // Rx authoring keys intentionally omitted for CLINIC_STAFF: API may enforce DOCTOR staffType for Rx; vets get create|edit|finalize via template overrides.
    {
      key: "CLINIC_STAFF",
      label: "Clinic Staff",
      scope: "BRANCH",
      permissionKeys: [
        "clinic.appointments.read","clinic.appointments.manage","clinic.patients.read","clinic.patients.manage",
        "clinic.visits.read","clinic.visits.manage",
        "clinic.settings.read","clinic.overview.read","clinic.services.manage",
        "clinic.queue.manage","clinic.queue.screen",
        "clinic.emr.read","clinic.emr.write",
        "clinic.prescription.read",
        "medicine.dose.record","medicine.dose.read","medicine.return.submit","medicine.return.verify","medicine.audit.bin.view",
        "injection.token.validate","injection.token.list",
        "clinic.rooms.view","clinic.analytics.view",
        "clinic.surgery.read","clinic.surgery.create","clinic.surgery.manage","clinic.surgery.notes.write",
      ],
    },
    {
      key: "CLINIC_RECEPTION",
      label: "Clinic Reception",
      scope: "BRANCH",
      permissionKeys: [
        "clinic.appointments.read","clinic.appointments.manage","clinic.appointments.collect_payment","clinic.appointments.assign_doctor","clinic.appointments.reprint",
        "clinic.patients.read","clinic.patients.manage",
        "clinic.queue.read","clinic.queue.manage","clinic.queue.screen",
        "clinic.billing.view","manager.billing.create_invoice","manager.billing.collect_payment",
        "injection.token.generate","injection.token.validate","injection.token.list",
        "customers.read",
        "clinic.prescription.read",
        "clinic.rooms.view","clinic.rooms.view_schedule","clinic.rooms.view_live","clinic.rooms.assign","clinic.rooms.reassign",
        "clinic.surgery.read","clinic.surgery.create","clinic.surgery.billing",
      ],
    },
    {
      key: "CLINIC_INVENTORY_STAFF",
      label: "Clinic Inventory Staff",
      scope: "BRANCH",
      permissionKeys: [
        "inventory.read","inventory.receive","clinic.inventory.issue","clinic.inventory.return","inventory.adjust",
        "clinic.catalog.view","clinic.catalog.search","clinic.catalog.branch_add","clinic.catalog.branch_remove",
        "clinic.sterilization.manage","clinic.audit.create","clinic.audit.view","clinic.wastage.report","clinic.refill.view","clinic.refill.convert",
        "manager.inventory.low_stock_alert",
      ],
    },
    // Producer Authentication System Roles
    {
      key: "PRODUCER_OWNER",
      label: "Producer Owner",
      scope: "ORG",
      permissionKeys: [
        "producer.org.read", "producer.org.write",
        "producer.kyc.submit", "producer.kyc.view",
        "producer.products.read", "producer.products.write",
        "producer.batches.read", "producer.batches.write", "producer.batches.print",
        "producer.codes.generate", "producer.codes.export",
        "producer.verification.read", "producer.analytics.read",
        "producer.tickets.read", "producer.tickets.write",
      ],
    },
    {
      key: "PRODUCER_MANAGER",
      label: "Producer Manager",
      scope: "ORG",
      permissionKeys: [
        "producer.org.read",
        "producer.kyc.view",
        "producer.products.read", "producer.products.write",
        "producer.batches.read", "producer.batches.write", "producer.batches.print",
        "producer.codes.generate", "producer.codes.export",
        "producer.verification.read", "producer.analytics.read",
        "producer.tickets.read", "producer.tickets.write",
      ],
    },
    {
      key: "PRODUCER_STAFF",
      label: "Producer Staff",
      scope: "ORG",
      permissionKeys: [
        "producer.products.read", "producer.products.write",
        "producer.batches.read", "producer.batches.print",
        "producer.codes.generate", "producer.codes.export",
        "producer.tickets.read", "producer.tickets.write",
      ],
    },
    {
      key: "PRODUCER_AUDITOR",
      label: "Producer Auditor",
      scope: "ORG",
      permissionKeys: [
        "producer.org.read",
        "producer.products.read",
        "producer.batches.read",
        "producer.verification.read",
        "producer.analytics.read",
        "producer.tickets.read",
      ],
    },
    {
      key: "PRODUCER_VIEWER",
      label: "Producer Viewer",
      scope: "ORG",
      permissionKeys: [
        "producer.org.read",
        "producer.products.read",
        "producer.batches.read",
        "producer.tickets.read",
      ],
    },
  ];

  // Upsert permissions
  const permMap = new Map<string, number>();
  for (const p of permissions) {
    const row = await prisma.permission.upsert({
      where: { key: p.key },
      update: { label: p.label, description: p.description || null },
      create: { key: p.key, label: p.label, description: p.description || null },
      select: { id: true, key: true },
    });
    permMap.set(row.key, row.id);
  }

  // Upsert roles
  const roleMap = new Map<string, number>();
  for (const r of roles) {
    const row = await prisma.role.upsert({
      where: { key: r.key },
      update: { label: r.label, scope: r.scope, isSystem: true },
      create: { key: r.key, label: r.label, scope: r.scope, isSystem: true },
      select: { id: true, key: true },
    });
    roleMap.set(row.key, row.id);
  }

  // Upsert role_permissions matrix
  for (const r of roles) {
    const roleId = roleMap.get(r.key)!;

    // ensure exact set (idempotent): create missing links; do not delete extras (safe)
    for (const pk of r.permissionKeys) {
      const permissionId = permMap.get(pk);
      if (!permissionId) continue;

      await prisma.rolePermission.upsert({
        where: { roleId_permissionId: { roleId, permissionId } },
        update: {},
        create: { roleId, permissionId },
      });
    }
  }

  // One-time verification: PRODUCER_STAFF has producer.products.write (for staff product create)
  const producerStaffRole = await prisma.role.findUnique({
    where: { key: "PRODUCER_STAFF" },
    include: { rolePermissions: { include: { permission: { select: { key: true } } } } },
  });
  const staffPermKeys = (producerStaffRole?.rolePermissions ?? []).map((rp) => rp.permission.key);
  const hasProductsWrite = staffPermKeys.includes("producer.products.write");
  console.log("[seedRolesPermissions] PRODUCER_STAFF has producer.products.write:", hasProductsWrite);
}
