/**
 * Branch Dashboard role → permission matrix.
 * Aligned with docs/dashboard/BRANCH_PERMISSION_MATRIX.md.
 * Used by resolveBranchAccessProfile to compute myAccess.permissions for the staff app.
 */

/** Role priority for deterministic selection (highest first). */
export const BRANCH_ROLE_PRIORITY = [
  "BRANCH_MANAGER",
  "WAREHOUSE_MANAGER",
  "DELIVERY_MANAGER",
  "ACCOUNTANT",
  "SELLER",
  "BRANCH_STAFF",
  "DISPATCH_STAFF",
  "RECEIVING_STAFF",
  "DELIVERY_STAFF",
  "CLINIC_STAFF",
  "CLINIC_RECEPTION",
  "CLINIC_INVENTORY_STAFF",
  "DOCTOR",
  "PHARMACIST",
  "GROOMING_STAFF",
  "BOARDING_STAFF",
  "TRAINING_STAFF",
] as const;

/** Base permissions always included when user has APPROVED branch access. */
export const BRANCH_BASE_PERMISSIONS = ["branch.view", "dashboard.view"];

/**
 * Permission keys per role for branch dashboard (sidebar, route guards).
 * Keys match BRANCH_PERMISSION_MATRIX.md and branchSidebarConfig requiredPerm.
 */
export const BRANCH_ROLE_PERMISSIONS: Record<string, string[]> = {
  BRANCH_MANAGER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "tasks.assign",
    "approvals.view",
    "approvals.manage",
    "inventory.read",
    "inventory.receive",
    "inventory.adjust",
    "inventory.transfer",
    "inventory.transfer.approve",
    "inventory.ledger.view",
    /** SHOP batch sell price + expiry (branch-scoped batch pricing rules; not global org pricing). */
    "inventory.batch.pricing",
    "pos.view",
    "pos.sell",
    "pos.refund",
    "pos.discount.override",
    "retail.discount.apply",
    "retail.discount.approve",
    "dispatch.receive.verify",
    "dispatch.receive.confirm.branch_manager",
    "grn.confirm.warehouse_manager",
    "cashdrawer.open",
    "cashdrawer.close",
    "services.view",
    "services.manage",
    "appointments.view",
    "appointments.manage",
    "customers.view",
    "customers.manage",
    "staff.view",
    "staff.manage",
    "shifts.view",
    "shifts.manage",
    "reports.view",
    "reports.export",
    "clinic.settings.read",
    "clinic.settings.write",
    "clinic.services.manage",
    "clinic.overview.read",
    "clinic.overview.manage",
    "clinic.rooms.manage",
    "clinic.rooms.update",
    "clinic.rooms.assign",
    "clinic.rooms.reassign",
    "clinic.rooms.view_schedule",
    "clinic.rooms.view_live",
    "clinic.rooms.manage_blocks",
    "clinic.rooms.mark_cleaning",
    "clinic.rooms.mark_occupied",
    "clinic.rooms.view_analytics",
    "clinic.rooms.view_audit",
    "clinic.rooms.emergency_override",
    "clinic.staff.manage",
    "clinic.schedule.manage",
    "clinic.holidays.manage",
    "clinic.emergency.manage",
    "clinic.fees.manage",
    "clinic.appointments.read",
    "clinic.appointments.manage",
    "clinic.queue.read",
    "clinic.queue.manage",
    "clinic.queue.screen",
    "clinic.patients.read",
    "clinic.patients.manage",
    "clinic.visits.read",
    "clinic.visits.manage",
    "clinic.emr.read",
    "clinic.emr.write",
    "clinic.prescription.read",
    "medicine.policy.read",
    "medicine.policy.manage",
    "medicine.dispense.request",
    "medicine.dispense.approve",
    "medicine.override.approve",
    "medicine.dispense.issue",
    "medicine.vial.open",
    "medicine.vial.activate",
    "medicine.vial.force_open",
    "medicine.vial.use",
    "medicine.vial.return",
    "medicine.dose.record",
    "medicine.dose.read",
    "injection.token.generate",
    "injection.token.validate",
    "injection.token.list",
    "injection.token.cancel",
    "injection.token.emergency_bypass",
    "medicine.reconciliation.run",
    "medicine.reconciliation.read",
    "medicine.reconciliation.acknowledge",
    "medicine.return.submit",
    "medicine.return.verify",
    "medicine.audit.bin.view",
    "medicine.audit.bin.manage",
    "medicine.destruction.approve",
    "clinic.packages.read",
    "clinic.packages.write",
    "clinic.discount.apply",
    "clinic.discount.approve",
    "clinic.settlement.read",
    "clinic.settlement.review",
    "clinic.settlement.approve",
    "clinic.settlement.pay",
    "clinic.cases.read",
    "clinic.cases.write",
    "clinic.supply.read",
    "clinic.supply.manage",
    "clinic.transfers.read",
    "clinic.transfers.receive",
    "clinic.sterilization.view",
    "clinic.sterilization.manage",
    "clinic.consumption.read",
    "clinic.consumption.write",
    "clinic.finance_config.read",
    "clinic.finance_config.write",
    "clinic.reports.profitability",
    "clinic.reports.settlement",
    "clinic.reports.discount",
    "clinic.reports.variance",
    "clinic.reports.doctor_contribution",
    "clinic.contracts.read",
    "clinic.contracts.write",
    // Manager Operations (enterprise branch manager control)
    "manager.appointments.create",
    "manager.appointments.assign_doctor",
    "manager.appointments.cancel",
    "manager.appointments.reschedule",
    "manager.walkin.register",
    "manager.patients.create",
    "manager.patients.edit",
    "manager.patients.view_history",
    "manager.inventory.update_stock",
    "manager.inventory.supply_request",
    "manager.inventory.purchase_request",
    "manager.inventory.low_stock_alert",
    "manager.services.enable_disable",
    "manager.packages.activate",
    "manager.discount.apply",
    "manager.pricing.view",
    "manager.staff.assign",
    "manager.staff.duty_roster",
    "manager.staff.leave_approve",
    "manager.staff.performance_view",
    "manager.billing.create_invoice",
    "manager.billing.collect_payment",
    "manager.billing.refund_request",
    "manager.reports.daily_revenue",
    "manager.reports.doctor_performance",
    "manager.reports.inventory_usage",
    "manager.reports.export",
    "manager.branch.settings",
    "manager.branch.hours",
    "manager.branch.announcements",
    "clinic.analytics.view",
    "clinic.stats.view",
    "clinic.doctors.view",
    "clinic.doctors.assign",
    "clinic.doctors.invite",
    "clinic.doctors.manage_schedule",
    "clinic.doctors.manage_services",
    "clinic.doctors.manage_packages",
    "clinic.doctors.manage_leave",
    "clinic.doctors.manage_credentials",
    "clinic.doctors.propose_fee",
    "clinic.doctors.request_activation",
    "clinic.doctors.view_performance",
    "clinic.doctors.view_audit",
    "clinic.doctors.approve_requests",
    "clinic.packages.delete",
    "clinic.packages.deactivate",
    "clinic.packages.items.manage",
    "clinic.catalog.view",
    "clinic.catalog.search",
    "clinic.catalog.branch_add",
    "clinic.catalog.branch_remove",
    "clinic.inventory.issue",
    "clinic.inventory.return",
    "clinic.audit.view",
    "clinic.rooms.view",
    "clinic.billing.view",
    "clinic.billing.adjust",
    "clinic.reports.branch_analytics",
  ],
  BRANCH_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "pos.view",
    "pos.sell",
    "customers.view",
    "reports.view",
  ],
  SELLER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "pos.view",
    "pos.sell",
    "retail.discount.apply",
    "customers.view",
    "reports.view",
  ],
  DELIVERY_MANAGER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "approvals.view",
    "inventory.read",
    "reports.view",
  ],
  DELIVERY_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
  ],
  /** Base branch role for clinic floor staff (nurses, etc.). Rx authoring is NOT granted here — clinic API requires DOCTOR staffType plus clinic.prescription.create|edit|finalize; assign CLINIC_DOCTOR template for veterinarians. */
  CLINIC_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "services.view",
    "appointments.view",
    "customers.view",
    "clinic.settings.read",
    "clinic.overview.read",
    "clinic.services.manage",
    "clinic.appointments.read",
    "clinic.appointments.manage",
    "clinic.queue.read",
    "clinic.queue.manage",
    "clinic.queue.screen",
    "clinic.patients.read",
    "clinic.patients.manage",
    "clinic.visits.read",
    "clinic.visits.manage",
    "clinic.emr.read",
    "clinic.emr.write",
    "clinic.prescription.read",
    "medicine.dose.record",
    "medicine.dose.read",
    "injection.token.validate",
    "injection.token.list",
    "medicine.return.submit",
    "medicine.return.verify",
    "medicine.audit.bin.view",
    "clinic.rooms.view",
    "clinic.analytics.view",
  ],
  CLINIC_RECEPTION: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "clinic.appointments.read",
    "clinic.appointments.manage",
    "clinic.appointments.collect_payment",
    "clinic.appointments.assign_doctor",
    "clinic.appointments.reprint",
    "clinic.patients.read",
    "clinic.patients.manage",
    "clinic.queue.read",
    "clinic.queue.manage",
    "clinic.queue.screen",
    "clinic.billing.view",
    "manager.billing.create_invoice",
    "manager.billing.collect_payment",
    "injection.token.generate",
    "injection.token.validate",
    "injection.token.list",
    "customers.view",
    "clinic.rooms.view",
    "clinic.rooms.view_schedule",
    "clinic.rooms.view_live",
    "clinic.rooms.assign",
    "clinic.rooms.reassign",
    "clinic.prescription.read",
  ],
  CLINIC_INVENTORY_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "inventory.receive",
    "clinic.inventory.issue",
    "clinic.inventory.return",
    "inventory.adjust",
    "clinic.items.read",
    "clinic.stock.read",
    "clinic.catalog.view",
    "clinic.catalog.search",
    "clinic.catalog.branch_add",
    "clinic.catalog.branch_remove",
    "clinic.sterilization.manage",
    "clinic.audit.create",
    "clinic.audit.view",
    "clinic.wastage.report",
    "clinic.refill.view",
    "clinic.refill.convert",
    "manager.inventory.low_stock_alert",
  ],
  DOCTOR: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "services.view",
    "appointments.view",
    "customers.view",
    "clinic.settings.read",
    "clinic.overview.read",
    "clinic.services.manage",
    "clinic.appointments.read",
    "clinic.appointments.manage",
    "clinic.queue.read",
    "clinic.queue.manage",
    "clinic.queue.screen",
    "clinic.patients.read",
    "clinic.patients.manage",
    "clinic.visits.read",
    "clinic.visits.manage",
    "clinic.emr.read",
    "clinic.emr.write",
    "clinic.prescription.read",
    "clinic.prescription.create",
    "clinic.prescription.edit",
    "clinic.prescription.finalize",
    "medicine.policy.read",
    "medicine.dispense.request",
    "medicine.dispense.approve",
    "medicine.override.approve",
    "medicine.dispense.issue",
    "medicine.vial.open",
    "medicine.vial.activate",
    "medicine.vial.force_open",
    "medicine.vial.use",
    "medicine.vial.return",
    "medicine.dose.record",
    "medicine.dose.read",
    "injection.token.generate",
    "injection.token.validate",
    "injection.token.list",
    "injection.token.cancel",
    "medicine.return.submit",
    "medicine.return.verify",
    "medicine.audit.bin.view",
    "clinic.rooms.view",
    "clinic.analytics.view",
    "clinic.surgery.read",
    "clinic.surgery.create",
    "clinic.surgery.manage",
    "clinic.surgery.notes.write",
  ],
  PHARMACIST: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "inventory.receive",
    "clinic.prescription.read",
    "clinic.catalog.view",
    "clinic.catalog.search",
    "medicine.policy.read",
    "medicine.dispense.request",
    "medicine.dispense.approve",
    "medicine.dispense.issue",
    "medicine.vial.open",
    "medicine.vial.use",
    "medicine.vial.return",
    "medicine.dose.record",
    "medicine.dose.read",
    "injection.token.validate",
    "injection.token.list",
  ],
  GROOMING_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "customers.view",
    "orders.read",
    "pos.view",
  ],
  BOARDING_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "customers.view",
    "orders.read",
    "pos.view",
  ],
  TRAINING_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "customers.view",
    "orders.read",
  ],
  ACCOUNTANT: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "approvals.view",
    "inventory.ledger.view",
    "pos.view",
    "pos.refund",
    "reports.view",
    "reports.export",
  ],
  WAREHOUSE_MANAGER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "approvals.view",
    "approvals.manage",
    "inventory.read",
    "inventory.receive",
    "inventory.adjust",
    "inventory.transfer",
    "inventory.transfer.approve",
    "inventory.ledger.view",
    "warehouse.view",
    "warehouse.manage",
    "warehouse.staff.manage",
    "warehouse.locations.manage",
    "warehouse.dashboard.view",
    "dispatch.view",
    "dispatch.create",
    "dispatch.manage",
    "delivery.view",
    "delivery.assign",
    "delivery.manage",
    "delivery.pod.submit",
    "procurement.po.view",
    "procurement.po.manage",
    "warehouse.allocation.manage",
    "warehouse.pick.execute",
    "qc.view",
    "qc.inspect",
    "qc.release",
    "quarantine.view",
    "quarantine.manage",
    "audit.view",
    "audit.export",
    "warehouse.zone.manage",
    "recall.allocation.release",
    "reports.view",
    "reports.export",
    "warehouse.operations",
    "warehouse.pick",
    "warehouse.qc",
    "warehouse.request.create",
    "inbound.read",
    "inbound.receive",
    "inbound.grn",
    "purchase.receive",
    "grn.view",
    "grn.create",
    "grn.post",
    "grn.confirm.warehouse_manager",
    "grn.void",
    "batch.manage",
    "barcode.manage",
    "distribution.view",
    "distribution.execute",
    "qc.execute",
    "dispatch.receive.verify",
    "dispatch.receive.confirm.branch_manager",
    "procurement.request.view",
    "procurement.request.manage",
  ],
  RECEIVING_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "inventory.receive",
    "warehouse.view",
    "warehouse.dashboard.view",
    "dispatch.view",
    "qc.view",
    "qc.inspect",
    "warehouse.operations",
    "warehouse.qc",
    "inbound.read",
    "inbound.receive",
    "inbound.grn",
    "purchase.receive",
    "grn.view",
    "grn.create",
    "grn.post",
    "grn.void",
    "batch.manage",
    "barcode.manage",
    "dispatch.receive.verify",
    "procurement.po.view",
    "procurement.request.view",
  ],
  DISPATCH_STAFF: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "warehouse.view",
    "warehouse.dashboard.view",
    "dispatch.view",
    "dispatch.create",
    "dispatch.manage",
    "delivery.view",
    "delivery.assign",
    "delivery.pod.submit",
    "warehouse.pick.execute",
    "warehouse.operations",
    "warehouse.pick",
  ],
  /** WarehouseStaffRole enum — permissions for assignment-only roles (invite / WSA). */
  INVENTORY_CONTROLLER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "inventory.receive",
    "inventory.adjust",
    "warehouse.view",
    "warehouse.dashboard.view",
    "warehouse.operations",
    "warehouse.locations.manage",
    "warehouse.manage",
  ],
  QC_OFFICER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "warehouse.view",
    "warehouse.dashboard.view",
    "warehouse.qc",
    "warehouse.operations",
    "qc.view",
    "qc.inspect",
    "qc.release",
    "quarantine.view",
    "quarantine.manage",
  ],
  AUDIT_OFFICER: [
    "branch.view",
    "dashboard.view",
    "tasks.view",
    "inventory.read",
    "warehouse.view",
    "warehouse.dashboard.view",
    "audit.view",
    "audit.export",
  ],
};

/** Default role when BranchMember.role is missing or unmapped. */
export const BRANCH_DEFAULT_ROLE = "BRANCH_STAFF";

const BRANCH_ROLE_PRIORITY_INDEX: Map<string, number> = new Map(
  BRANCH_ROLE_PRIORITY.map((k, i) => [k, i])
);

/** Minimal member shape for role resolution (Prisma select / plain objects). */
export type BranchMemberRolePickInput = {
  role?: string | null;
  roles?: Array<{ role?: { key?: string | null } | null } | null> | null;
};

/**
 * When a user has multiple rows in `branch_member_roles`, Prisma order is not guaranteed.
 * Pick the role with the highest privilege (lowest index in BRANCH_ROLE_PRIORITY) so
 * e.g. BRANCH_MANAGER wins over CLINIC_STAFF when both are assigned — aligns JWT, /branches/:id/me, and services.
 */
export function pickEffectiveBranchRoleKey(
  member: BranchMemberRolePickInput | null | undefined,
  fallback: string = BRANCH_DEFAULT_ROLE
): string {
  if (!member) return fallback;
  const keys: string[] = [];
  if (Array.isArray(member.roles)) {
    for (const row of member.roles) {
      const k = row?.role?.key;
      if (k && typeof k === "string") keys.push(String(k));
    }
  }
  if (member.role) keys.push(String(member.role));
  if (!keys.length) return fallback;
  let best = keys[0];
  let bestIdx = BRANCH_ROLE_PRIORITY_INDEX.has(best) ? BRANCH_ROLE_PRIORITY_INDEX.get(best)! : 999;
  for (let i = 1; i < keys.length; i++) {
    const k = keys[i];
    const idx = BRANCH_ROLE_PRIORITY_INDEX.has(k) ? BRANCH_ROLE_PRIORITY_INDEX.get(k)! : 999;
    if (idx < bestIdx) {
      bestIdx = idx;
      best = k;
    }
  }
  return best;
}

/** Default permissions when role has no entry (minimal view). */
export const BRANCH_DEFAULT_PERMISSIONS = [
  "branch.view",
  "dashboard.view",
  "tasks.view",
  "inventory.read",
  "customers.view",
];

/**
 * Clinic role templates: templateKey -> permissions (additive overrides for BranchAccessPermission).
 * Used when assigning a clinic role template to a staff member; staffType is set on ClinicStaffProfile.
 */
export const CLINIC_ROLE_TEMPLATE_PERMISSIONS: Record<string, string[]> = {
  /** Vets: merged into BranchAccessPermission.permissionOverrides; pairs with ClinicStaffProfile.staffType DOCTOR. */
  CLINIC_DOCTOR: [
    "service.read", "clinic.appointments.read", "clinic.patients.read", "clinic.queue.manage",
    "clinic.visits.read", "clinic.visits.manage", "clinic.emr.read", "clinic.emr.write",
    "clinic.prescription.read",
    "clinic.prescription.create",
    "clinic.prescription.edit",
    "clinic.prescription.finalize",
    "medicine.dispense.request", "medicine.vial.open", "medicine.vial.use",
    "injection.token.validate", "injection.token.list",
  ],
  CLINIC_NURSE: [
    "clinic.appointments.read", "clinic.patients.read", "clinic.queue.manage", "clinic.queue.screen",
    "clinic.prescription.read",
    "medicine.dispense.request", "medicine.vial.use", "medicine.vial.return",
    "medicine.dose.record", "medicine.dose.read", "medicine.return.submit", "medicine.return.verify",
    "injection.token.validate", "injection.token.list",
  ],
  CLINIC_RECEPTION: [
    "clinic.appointments.read", "clinic.patients.read", "clinic.appointments.manage",
    "clinic.appointments.collect_payment", "clinic.appointments.reprint", "clinic.appointments.assign_doctor",
    "clinic.queue.manage", "clinic.queue.screen",
    "clinic.billing.view", "manager.billing.create_invoice", "manager.billing.collect_payment",
    "clinic.prescription.read",
    "injection.token.generate", "injection.token.validate", "injection.token.list",
  ],
  CLINIC_INVENTORY_STAFF: [
    "inventory.read", "inventory.receive", "clinic.inventory.issue", "clinic.inventory.return", "inventory.adjust",
    "clinic.catalog.view", "clinic.catalog.search", "clinic.catalog.branch_add", "clinic.catalog.branch_remove",
    "clinic.sterilization.manage", "clinic.audit.create", "clinic.audit.view",
    "clinic.wastage.report", "clinic.refill.view", "clinic.refill.convert",
    "manager.inventory.low_stock_alert",
  ],
  CLINIC_LAB: ["clinic.patients.read"],
  CLINIC_GROOMER: ["service.read"],
  PHARMACY_STAFF: [
    "medicine.policy.read", "medicine.dispense.approve", "medicine.dispense.issue",
    "medicine.vial.open", "medicine.vial.activate", "medicine.vial.force_open", "medicine.vial.use", "medicine.vial.return",
    "injection.token.list",
    "medicine.return.verify", "medicine.audit.bin.view", "medicine.audit.bin.manage",
  ],
  CLINIC_MANAGER: [
    "clinic.overview.read",
    "clinic.settings.read",
    "clinic.settings.write",
    "clinic.packages.read",
    "clinic.packages.write",
    "clinic.discount.apply",
    "clinic.discount.approve",
    "clinic.settlement.read",
    "clinic.settlement.review",
    "clinic.cases.read",
    "clinic.cases.write",
    "clinic.supply.read",
    "clinic.supply.manage",
    "clinic.transfers.read",
    "clinic.transfers.receive",
    "clinic.sterilization.view",
    "clinic.sterilization.manage",
    "clinic.consumption.read",
    "clinic.consumption.write",
    "clinic.finance_config.read",
    "clinic.reports.profitability",
    "clinic.reports.settlement",
    "clinic.reports.discount",
    "clinic.reports.variance",
    "clinic.reports.doctor_contribution",
    "clinic.contracts.read",
    "clinic.services.manage",
    "clinic.rooms.manage",
    "clinic.staff.manage",
    "clinic.schedule.manage",
    "clinic.fees.manage",
    "clinic.holidays.manage",
    "clinic.emergency.manage",
    "clinic.appointments.manage",
    "clinic.appointments.collect_payment", "clinic.appointments.apply_discount",
    "clinic.appointments.reprint", "clinic.appointments.assign_doctor",
    "clinic.queue.manage",
    "clinic.queue.screen",
    "medicine.policy.read",
    "medicine.policy.manage",
    "medicine.dispense.request",
    "medicine.dispense.approve",
    "medicine.override.approve",
    "medicine.dispense.issue",
    "medicine.vial.open",
    "medicine.vial.activate",
    "medicine.vial.force_open",
    "medicine.vial.use",
    "medicine.vial.return",
    "medicine.dose.record",
    "medicine.dose.read",
    "injection.token.generate",
    "injection.token.validate",
    "injection.token.list",
    "injection.token.cancel",
    "injection.token.emergency_bypass",
    "medicine.reconciliation.run",
    "medicine.reconciliation.read",
    "medicine.reconciliation.acknowledge",
    "medicine.return.submit",
    "medicine.return.verify",
    "medicine.audit.bin.view",
    "medicine.audit.bin.manage",
    "medicine.destruction.approve",
  ],
};
