-- Add Trust & Safety enforcement notification types
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ENFORCEMENT_CODE_BLOCKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ENFORCEMENT_BATCH_QUARANTINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ENFORCEMENT_PRODUCT_DEACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ENFORCEMENT_ORG_SUSPENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ENFORCEMENT_ACTION_REVERTED';
