-- Phase 2: Batch lifecycle - expand AuthBatchStatus, add review/void fields to AuthBatch
ALTER TYPE "AuthBatchStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "AuthBatchStatus" ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';
ALTER TYPE "AuthBatchStatus" ADD VALUE IF NOT EXISTS 'CODES_ALLOCATED';
ALTER TYPE "AuthBatchStatus" ADD VALUE IF NOT EXISTS 'PRINTED';
ALTER TYPE "AuthBatchStatus" ADD VALUE IF NOT EXISTS 'VOIDED';
ALTER TYPE "AuthBatchStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';

ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "reviewedByAdminId" INTEGER;
ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "reviewNotes" TEXT;
ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "voidedAt" TIMESTAMP(3);
ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "voidedByUserId" INTEGER;
ALTER TABLE "auth_batches" ADD COLUMN IF NOT EXISTS "voidReason" TEXT;
