/**
 * Human-readable permissions registry (grouped).
 * Keys aligned with:
 *   - bpa_web/src/lib/permissionMenu.ts (required[] on menu items)
 *   - bpa_web/src/larkon-admin/menu/adapters/adminRouteMap.ts (admin routes)
 *   - PRODUCER_GOVERNANCE_MASTER_PLAN.md §3.3 (admin.producers.*, admin.approvals.*, producer.*)
 * Any permission used in UI but not discoverable from the above is added manually with a comment.
 */

export type PermissionScope = "admin" | "producer" | "both" | "branch" | "org";

export type PermissionEntry = {
  key: string;
  label: string;
  group: string;
  description: string;
  scope: PermissionScope;
};

/** Ordered groups for display. Each group contains permissions in display order. */
const REGISTRY: PermissionEntry[] = [
  // ----- Admin (Governance) — Master plan §3.3 -----
  { key: "admin.producers.read", label: "View producers", group: "Governance", description: "List and view producer organizations and details.", scope: "admin" },
  { key: "admin.producers.write", label: "Manage producers", group: "Governance", description: "Suspend, unsuspend, and update flags/quotas for producer orgs.", scope: "admin" },
  { key: "admin.approvals.manage", label: "Manage approvals", group: "Governance", description: "Approve or reject pending producer product/batch approvals.", scope: "admin" },
  { key: "admin.governance.products.review", label: "Review products", group: "Governance", description: "Take/release reviewer lock on product approvals.", scope: "admin" },
  { key: "admin.governance.products.approve", label: "Approve products", group: "Governance", description: "Approve or activate producer products.", scope: "admin" },
  { key: "admin.governance.products.request_changes", label: "Request product changes", group: "Governance", description: "Request changes on submitted/under-review products.", scope: "admin" },
  { key: "admin.governance.products.archive", label: "Archive products", group: "Governance", description: "Archive or unarchive rejected/inactive products.", scope: "admin" },
  { key: "admin.governance.batches.review", label: "Review batches", group: "Governance", description: "Review batch submissions.", scope: "admin" },
  { key: "admin.governance.batches.approve", label: "Approve batches", group: "Governance", description: "Approve or reject batches.", scope: "admin" },
  { key: "admin.governance.batches.allocate_codes", label: "Allocate codes", group: "Governance", description: "Allow code allocation for batches.", scope: "admin" },
  { key: "admin.governance.batches.void", label: "Void batches", group: "Governance", description: "Void batches (no verified codes).", scope: "admin" },
  { key: "admin.governance.enforcement.hide", label: "Hide products", group: "Governance", description: "Hide/unhide products (enforcement).", scope: "admin" },
  { key: "admin.governance.enforcement.freeze", label: "Freeze batches", group: "Governance", description: "Freeze batch printing/export.", scope: "admin" },
  { key: "admin.governance.enforcement.suspend", label: "Suspend producers", group: "Governance", description: "Suspend producer org with incident.", scope: "admin" },
  { key: "admin.governance.enforcement.cases", label: "Trust & Safety cases", group: "Governance", description: "Manage complaint cases, evidence, and trace.", scope: "admin" },
  { key: "admin.governance.enforcement.actions", label: "Enforcement actions", group: "Governance", description: "Apply or revert enforcement actions (freeze, quarantine, suspend).", scope: "admin" },
  { key: "admin.governance.incidents.manage", label: "Manage incidents", group: "Governance", description: "Create and resolve governance incidents.", scope: "admin" },
  { key: "admin.governance.analytics.read", label: "Governance analytics", group: "Governance", description: "View governance analytics.", scope: "admin" },
  { key: "admin.governance.code.search", label: "Code lookup", group: "Governance", description: "Search codes and trace producer/product/batch.", scope: "admin" },
  { key: "admin.kyc.manage", label: "Manage KYC", group: "Governance", description: "Review and decide on producer KYC verification.", scope: "admin" },
  { key: "admin.audit.read", label: "View audit logs", group: "Governance", description: "Read audit timeline and governance events.", scope: "admin" },
  { key: "admin.permissions.read", label: "View permissions registry", group: "Governance", description: "View human-readable permissions registry (grouped).", scope: "admin" },
  // ----- Support (ticketing) -----
  { key: "admin.support.tickets.manage", label: "Manage support tickets", group: "Support", description: "List, view, update, assign, and add internal notes on tickets.", scope: "admin" },
  { key: "admin.support.tickets.respond", label: "Respond to tickets", group: "Support", description: "Post public replies to producer tickets.", scope: "admin" },
  { key: "admin.support.tickets.assign", label: "Assign tickets", group: "Support", description: "Assign tickets to support agents.", scope: "admin" },
  { key: "admin.support.tickets.escalate", label: "Escalate to enforcement", group: "Support", description: "Escalate ticket to Trust & Safety case.", scope: "admin" },
  { key: "producer.tickets.read", label: "View support tickets", group: "Support", description: "View own org support tickets and messages.", scope: "producer" },
  { key: "producer.tickets.write", label: "Create and reply to tickets", group: "Support", description: "Create tickets, reply, close, and reopen.", scope: "producer" },
  // ----- Producer panel (permissionMenu producer section) -----
  { key: "producer.org.read", label: "Producer org access", group: "Producer", description: "Access producer org context (approvals, staff).", scope: "producer" },
  // Producer governance groups (Batch, Product, KYC, Codes, Printing) — backend enforcement keys; not always in menu required[]
  { key: "producer.batches.enabled", label: "Batch creation", group: "Batch", description: "Feature flag: allow creating batches.", scope: "producer" },
  { key: "producer.products.enabled", label: "Product management", group: "Product", description: "Feature flag: allow product operations.", scope: "producer" },
  { key: "producer.printing.enabled", label: "Printing", group: "Printing", description: "Feature flag: allow print batch operations.", scope: "producer" },
  { key: "producer.codes.export.enabled", label: "Code export", group: "Codes", description: "Feature flag: allow code export.", scope: "producer" },
  { key: "producer.staff.invites.enabled", label: "Staff invites", group: "Producer", description: "Feature flag: allow staff invites.", scope: "producer" },
  // ----- Owner / shared (permissionMenu owner REGISTRY required[]) -----
  { key: "org.read", label: "View organizations", group: "My Business", description: "View organizations and org details.", scope: "both" },
  { key: "org.create", label: "Create organization", group: "My Business", description: "Create new organization.", scope: "both" },
  { key: "branch.read", label: "View branches", group: "My Business", description: "View branches.", scope: "both" },
  { key: "branch.create", label: "Create branch", group: "My Business", description: "Create new branch.", scope: "both" },
  { key: "staff.read", label: "View staff", group: "My Business", description: "View staff and access controls.", scope: "both" },
  { key: "staff.create", label: "Invite staff", group: "My Business", description: "Invite and create staff.", scope: "both" },
  { key: "product.read", label: "View products", group: "Products", description: "View products and catalog.", scope: "both" },
  { key: "product.create", label: "Create product", group: "Products", description: "Create and edit products.", scope: "both" },
  { key: "inventory.read", label: "View inventory", group: "Inventory", description: "View stock and inventory.", scope: "both" },
  { key: "inventory.receive", label: "Receive stock", group: "Inventory", description: "Receive stock at branch.", scope: "both" },
  { key: "inventory.adjust", label: "Adjust inventory", group: "Inventory", description: "Create and approve inventory adjustments.", scope: "both" },
  { key: "inventory.transfer", label: "Transfer inventory", group: "Inventory", description: "Create and manage inter-branch transfers.", scope: "both" },
  { key: "inventory.ai.forecast.read", label: "AI demand forecast", group: "Inventory", description: "View explainable demand forecasts and trends.", scope: "both" },
  { key: "inventory.ai.replenishment.manage", label: "AI replenishment", group: "Inventory", description: "View, accept, or dismiss AI replenishment suggestions.", scope: "both" },
  { key: "inventory.ai.procurement.read", label: "AI procurement intel", group: "Inventory", description: "View ranked vendor recommendations for at-risk SKUs.", scope: "both" },
  { key: "inventory.ai.control_tower.read", label: "Inventory control tower", group: "Inventory", description: "View cross-branch inventory KPIs and alerts.", scope: "both" },
  { key: "inventory.executive_tower.read", label: "Executive network command (Wave-5)", group: "Inventory", description: "Unified KPIs, drill-downs, scenarios, and decision package inbox.", scope: "both" },
  { key: "inventory.executive_tower.manage", label: "Executive tower actions", group: "Inventory", description: "Synthesize decision packages, approve or override, run what-if scenarios.", scope: "both" },
  { key: "inventory.financial.read", label: "Financial intelligence & CTS", group: "Inventory", description: "View cost-to-serve, cost facts, and financial rollups.", scope: "both" },
  { key: "inventory.slo.read", label: "Service level (SLO) dashboard", group: "Inventory", description: "View SLO definitions and measurements.", scope: "both" },
  { key: "operations.command_center.read", label: "Exception command center", group: "Operations", description: "View unified operational exceptions inbox.", scope: "both" },
  { key: "operations.command_center.manage", label: "Manage exception queue", group: "Operations", description: "Assign, acknowledge, resolve exceptions and RCA.", scope: "both" },
  { key: "admin.vendor.analytics.read", label: "Vendor analytics", group: "Governance", description: "View aggregate vendor performance metrics (admin).", scope: "admin" },
  { key: "warehouse.view", label: "View warehouses", group: "Warehouse", description: "List warehouses and open warehouse workspace.", scope: "both" },
  { key: "warehouse.manage", label: "Manage warehouses", group: "Warehouse", description: "Create and edit warehouse records.", scope: "both" },
  { key: "warehouse.operations", label: "Warehouse operations hub", group: "Warehouse", description: "Access warehouse operations dashboard and putaway queue.", scope: "both" },
  { key: "putaway.execute", label: "Execute putaway", group: "Warehouse", description: "Confirm putaway tasks and move stock to storage locations.", scope: "both" },
  { key: "warehouse.staff.manage", label: "Warehouse staff", group: "Warehouse", description: "Assign warehouse staff roles.", scope: "both" },
  { key: "warehouse.locations.manage", label: "Warehouse locations", group: "Warehouse", description: "Link inventory locations to a warehouse.", scope: "both" },
  { key: "warehouse.dashboard.view", label: "Warehouse dashboard", group: "Warehouse", description: "View warehouse KPIs and operational summary.", scope: "both" },
  { key: "inbound.read", label: "View inbound", group: "Warehouse", description: "View inbound queue and receipts context.", scope: "both" },
  { key: "inbound.receive", label: "Receive inbound", group: "Warehouse", description: "Receive stock into warehouse locations.", scope: "both" },
  { key: "inbound.grn", label: "Inbound GRN", group: "Warehouse", description: "Record GRN against inbound.", scope: "both" },
  { key: "purchase.receive", label: "Purchase receive", group: "Warehouse", description: "Receive vendor stock against purchase orders (GRN).", scope: "both" },
  { key: "grn.view", label: "View GRNs", group: "Warehouse", description: "View goods receipt notes and lines.", scope: "both" },
  { key: "grn.create", label: "Create GRNs", group: "Warehouse", description: "Create draft GRNs.", scope: "both" },
  { key: "grn.post", label: "Post GRNs", group: "Warehouse", description: "Post/receive GRNs into inventory.", scope: "both" },
  { key: "grn.confirm.warehouse_manager", label: "Confirm vendor GRN post", group: "Warehouse", description: "Finalize vendor/PO GRN after verification (ledger post).", scope: "both" },
  { key: "grn.void", label: "Void GRNs", group: "Warehouse", description: "Void draft GRNs before posting.", scope: "both" },
  { key: "batch.manage", label: "GRN batch/lot", group: "Warehouse", description: "Edit lot/expiry/batch fields on receive.", scope: "both" },
  { key: "barcode.manage", label: "GRN barcodes", group: "Warehouse", description: "Capture supplier/receive barcodes on GRN lines.", scope: "both" },
  { key: "distribution.view", label: "Distribution recommendations", group: "Warehouse", description: "View DC-to-branch transfer suggestions.", scope: "both" },
  { key: "distribution.execute", label: "Execute distribution", group: "Warehouse", description: "Accept or dismiss distribution recommendations.", scope: "both" },
  { key: "qc.execute", label: "Execute QC", group: "Warehouse", description: "Submit QC inspections (paired with qc.inspect).", scope: "both" },
  { key: "outbound.read", label: "View outbound", group: "Warehouse", description: "View outbound / dispatch queue.", scope: "both" },
  { key: "outbound.dispatch", label: "Dispatch outbound", group: "Warehouse", description: "Create and progress stock dispatches.", scope: "both" },
  { key: "outbound.pack", label: "Pack outbound", group: "Warehouse", description: "Pack lines for outbound dispatch.", scope: "both" },
  { key: "dispatch.view", label: "View dispatches", group: "Warehouse", description: "View stock dispatch documents.", scope: "both" },
  { key: "dispatch.create", label: "Create dispatches", group: "Warehouse", description: "Create new stock dispatches.", scope: "both" },
  { key: "dispatch.manage", label: "Manage dispatches", group: "Warehouse", description: "Update dispatch status and logistics fields.", scope: "both" },
  { key: "dispatch.receive.verify", label: "Dispatch receive verification", group: "Warehouse", description: "Save branch receive draft without posting stock.", scope: "both" },
  { key: "dispatch.receive.confirm.branch_manager", label: "Confirm dispatch receive", group: "Warehouse", description: "Post branch stock from verified dispatch receive.", scope: "both" },
  { key: "delivery.view", label: "View deliveries", group: "Warehouse", description: "View delivery assignments.", scope: "both" },
  { key: "delivery.assign", label: "Assign deliveries", group: "Warehouse", description: "Assign drivers to dispatch deliveries.", scope: "both" },
  { key: "delivery.manage", label: "Manage deliveries", group: "Warehouse", description: "Progress delivery assignment lifecycle.", scope: "both" },
  { key: "procurement.po.view", label: "View purchase orders", group: "Warehouse", description: "List and read purchase orders.", scope: "both" },
  { key: "procurement.po.manage", label: "Manage purchase orders", group: "Warehouse", description: "Create, approve, and cancel purchase orders.", scope: "both" },
  { key: "procurement.demand.view", label: "View procurement demand", group: "Warehouse", description: "Allocation shortage lines pending PO/GRN.", scope: "both" },
  { key: "procurement.demand.manage", label: "Manage procurement demand", group: "Warehouse", description: "Link demand to PO lines and cancel demand.", scope: "both" },
  { key: "procurement.demand.link_po", label: "Link demand to PO line", group: "Warehouse", description: "Attach shortage demand to a purchase order line.", scope: "both" },
  { key: "fulfillment.backorder.view", label: "View backorder status", group: "Warehouse", description: "See branch line backorder / procurement state.", scope: "both" },
  { key: "fulfillment.backorder.process", label: "Process backorder hooks", group: "Warehouse", description: "Trigger procurement-demand processing after GRN.", scope: "both" },
  { key: "warehouse.allocation.manage", label: "Allocation plans", group: "Warehouse", description: "Create allocation plans and run FEFO.", scope: "both" },
  { key: "warehouse.pick.execute", label: "Execute pick lists", group: "Warehouse", description: "Pick, complete pick lists, and handoff to dispatch.", scope: "both" },
  { key: "delivery.pod.submit", label: "Submit proof of delivery", group: "Warehouse", description: "Complete deliveries with POD capture.", scope: "both" },
  { key: "qc.view", label: "View QC queue", group: "Warehouse", description: "View inbound QC inspections and status.", scope: "both" },
  { key: "qc.inspect", label: "Perform QC inspection", group: "Warehouse", description: "Submit pass/fail QC results and dispositions.", scope: "both" },
  { key: "qc.release", label: "Release from quarantine", group: "Warehouse", description: "Move approved quarantine stock back to storage.", scope: "both" },
  { key: "quarantine.view", label: "View quarantine", group: "Warehouse", description: "View quarantine holdings and inspection links.", scope: "both" },
  { key: "quarantine.manage", label: "Manage quarantine", group: "Warehouse", description: "Release or dispose quarantined stock.", scope: "both" },
  { key: "audit.view", label: "Warehouse audit trail", group: "Warehouse", description: "View warehouse audit and escalation events.", scope: "both" },
  { key: "audit.export", label: "Export warehouse audit CSV", group: "Warehouse", description: "Download CSV of warehouse audit events.", scope: "both" },
  { key: "warehouse.zone.manage", label: "Warehouse zones", group: "Warehouse", description: "Define zones and assign locations to bins.", scope: "both" },
  { key: "recall.allocation.release", label: "Release recall allocation freeze", group: "Warehouse", description: "Allow FEFO/dispatch under active recall after authorization.", scope: "both" },
  { key: "orders.read", label: "View orders", group: "Orders", description: "View orders.", scope: "both" },
  { key: "orders.create", label: "Create orders", group: "Orders", description: "Create orders (e.g. POS).", scope: "both" },
  { key: "customers.read", label: "View customers", group: "People", description: "View customers.", scope: "both" },
  { key: "customers.view", label: "View customers (branch)", group: "People", description: "View customers in staff branch context.", scope: "both" },
  { key: "reports.read", label: "View reports", group: "Reports", description: "View reports and analytics.", scope: "both" },
  { key: "reports.view", label: "View reports (branch)", group: "Reports", description: "View reports in staff branch context.", scope: "both" },
  { key: "pricing.central.read", label: "View central pricing & governance", group: "Pricing", description: "Read org pricing governance policy and central price context (no catalog edits).", scope: "org" },
  { key: "pricing.central.write", label: "Central catalog pricing", group: "Pricing", description: "Set org MRP/base/floor on product pricing.", scope: "org" },
  { key: "pricing.branch.override", label: "Branch price overrides", group: "Pricing", description: "Set branch overrides within central band when enforced.", scope: "both" },
  { key: "pricing.audit.view", label: "Pricing audit", group: "Pricing", description: "View pricing change audit log.", scope: "org" },
  { key: "pricing.retail.rule.manage", label: "Retail discount rules", group: "Pricing", description: "Manage retail discount caps and approval thresholds.", scope: "org" },
  { key: "retail.discount.apply", label: "Apply retail discounts", group: "Pricing", description: "Apply POS/retail line discounts subject to rules.", scope: "branch" },
  { key: "retail.discount.approve", label: "Approve retail discounts", group: "Pricing", description: "Approve over-threshold retail discounts.", scope: "branch" },
  { key: "pricing.campaign.manage", label: "Manage pricing campaigns", group: "Pricing", description: "Create and publish retail pricing campaigns.", scope: "org" },
  { key: "pricing.membership.manage", label: "Manage membership tiers", group: "Pricing", description: "Configure membership discount tiers and exclusions.", scope: "org" },
  { key: "pricing.branch.override.request", label: "Request branch price override", group: "Pricing", description: "Submit branch special price requests for approval.", scope: "branch" },
  { key: "pricing.branch.override.approve", label: "Approve branch price overrides", group: "Pricing", description: "Review branch override requests and publish overrides.", scope: "org" },
  { key: "pricing.approval.matrix.manage", label: "Manage pricing approval matrix", group: "Pricing", description: "Configure role-based pricing approval routing.", scope: "org" },
  { key: "pricing.emergency.override", label: "Emergency price override", group: "Pricing", description: "Issue time-limited emergency POS price tokens.", scope: "org" },
  { key: "pricing.analytics.view", label: "Pricing analytics", group: "Pricing", description: "View margin, discount, and campaign analytics.", scope: "org" },
  { key: "pricing.bulk.import", label: "Bulk price import", group: "Pricing", description: "Import or bulk-update catalog prices.", scope: "org" },
  { key: "settings.read", label: "View settings", group: "Settings", description: "View settings.", scope: "both" },
  // ----- Staff Branch (branchSidebarConfig) -----
  { key: "dashboard.view", label: "View dashboard", group: "Staff Branch", description: "View branch dashboard.", scope: "both" },
  { key: "tasks.view", label: "View tasks", group: "Staff Branch", description: "View and manage tasks.", scope: "both" },
  { key: "approvals.view", label: "View approvals", group: "Staff Branch", description: "View pending approvals.", scope: "both" },
  { key: "pos.view", label: "View POS", group: "Staff Branch", description: "Access POS / sales.", scope: "both" },
  { key: "pos.sell", label: "Complete POS sales", group: "Staff Branch", description: "Create carts, add lines, finalize sales.", scope: "branch" },
  { key: "pos.refund", label: "POS refunds / full cancel", group: "Staff Branch", description: "Line returns and full order cancel at branch POS.", scope: "branch" },
  { key: "pos.discount.override", label: "POS discount override", group: "Staff Branch", description: "Apply custom discounts beyond cashier presets (with governance).", scope: "branch" },
  { key: "cashdrawer.open", label: "Open cash drawer shift", group: "Staff Branch", description: "Open POS shift / starting cash.", scope: "branch" },
  { key: "cashdrawer.close", label: "Close cash drawer shift", group: "Staff Branch", description: "Close POS shift and count cash.", scope: "branch" },
  { key: "staff.view", label: "View staff", group: "Staff Branch", description: "View staff and shifts.", scope: "both" },
  { key: "clinic.overview.manage", label: "Manage clinic overview", group: "Clinic Setup", description: "Manage clinic overview and settings.", scope: "both" },
  { key: "settings.manage", label: "Manage settings", group: "Settings", description: "Change settings.", scope: "both" },
  // ----- Vaccination Campaign 2026 (BPA national campaign module) -----
  { key: "campaign.manage", label: "Manage vaccination campaigns", group: "Vaccination Campaign", description: "Create, configure, publish, and operate BPA vaccination campaigns (locations, slots, staff).", scope: "admin" },
  { key: "campaign.view", label: "View vaccination campaigns", group: "Vaccination Campaign", description: "Read campaign configuration, bookings, and reports.", scope: "admin" },
  // ----- Clinic (permissionMenu clinic) -----
  { key: "service.read", label: "View services", group: "Clinic", description: "View clinic service catalog.", scope: "both" },
  { key: "clinic.appointments.read", label: "View appointments", group: "Clinic", description: "View clinic appointments.", scope: "both" },
  { key: "clinic.appointments.manage", label: "Manage appointments", group: "Clinic", description: "Create, cancel, reschedule appointments; check-in, no-show.", scope: "both" },
  { key: "clinic.appointments.collect_payment", label: "Collect payment", group: "Clinic", description: "Collect payment for appointments.", scope: "branch" },
  { key: "clinic.appointments.apply_discount", label: "Apply discount", group: "Clinic", description: "Apply discount on appointment payment.", scope: "branch" },
  { key: "clinic.appointments.reprint", label: "Reprint slips", group: "Clinic", description: "Reprint appointment or payment slips.", scope: "branch" },
  { key: "clinic.appointments.assign_doctor", label: "Assign doctor", group: "Clinic", description: "Assign doctor to Any Doctor appointments.", scope: "branch" },
  { key: "clinic.queue.read", label: "View queue", group: "Clinic", description: "View queue tickets and session.", scope: "both" },
  { key: "clinic.queue.manage", label: "Manage queue", group: "Clinic", description: "Issue tokens, call next, assign doctor, set priority, complete tickets.", scope: "both" },
  { key: "clinic.queue.screen", label: "View queue screen", group: "Clinic", description: "View PII-safe waiting screen (kiosk).", scope: "both" },
  { key: "clinic.patients.read", label: "View patients", group: "Clinic", description: "View clinic patients.", scope: "both" },
  { key: "clinic.patients.manage", label: "Manage patients", group: "Clinic", description: "Register and update pet/patient profiles.", scope: "both" },
  { key: "clinic.visits.read", label: "View visits", group: "Clinic", description: "View clinic visits and EMR.", scope: "both" },
  { key: "clinic.visits.manage", label: "Manage visits", group: "Clinic", description: "Create and update visits, vitals, notes.", scope: "both" },
  { key: "clinic.emr.read", label: "View EMR", group: "Clinic", description: "View visits, vitals, and clinical notes.", scope: "both" },
  { key: "clinic.emr.write", label: "Write EMR", group: "Clinic", description: "Create and update visits, vitals, SOAP notes.", scope: "both" },
  { key: "clinic.prescription.read", label: "View prescriptions", group: "Clinic", description: "View prescriptions and verify by QR.", scope: "both" },
  {
    key: "clinic.prescription.write",
    label: "Write prescriptions [RETIRED from API]",
    group: "Clinic",
    description:
      "RETIRED — clinic authoring routes accept only clinic.prescription.create | .edit | .finalize. This key remains in the registry for historical DB rows and admin display; it does not unlock any clinic prescription mutation. Re-assign vets to explicit keys; run scripts/migrate-prescription-write-overrides.ts for BranchAccessPermission JSON overrides.",
    scope: "both",
  },
  {
    key: "clinic.prescription.create",
    label: "Create prescriptions",
    group: "Clinic",
    description: "PRESCRIPTION_CREATE — clinic API also requires ClinicStaffProfile.staffType DOCTOR (middleware). Doctor panel uses /api/v1/doctor/*.",
    scope: "both",
  },
  {
    key: "clinic.prescription.edit",
    label: "Edit draft prescriptions",
    group: "Clinic",
    description: "PRESCRIPTION_EDIT — draft only; clinic API also requires DOCTOR staffType + prescriber match.",
    scope: "both",
  },
  {
    key: "clinic.prescription.finalize",
    label: "Finalize prescriptions",
    group: "Clinic",
    description: "PRESCRIPTION_FINALIZE — draft only; clinic API also requires DOCTOR staffType + prescriber match.",
    scope: "both",
  },
  { key: "clinic.prescription.delete", label: "Delete prescriptions", group: "Clinic", description: "PRESCRIPTION_DELETE — reserved for future doctor-only delete.", scope: "both" },
  { key: "clinic.lab.read", label: "View lab", group: "Clinic", description: "View lab requisitions and reports.", scope: "both" },
  { key: "clinic.lab.write", label: "Write lab", group: "Clinic", description: "Create requisitions and enter report results.", scope: "both" },
  // ----- Medicine Control (CCMLPA) -----
  { key: "medicine.policy.read", label: "View medicine policies", group: "Medicine Control", description: "View medicine policy and vial control rules.", scope: "both" },
  { key: "medicine.policy.manage", label: "Manage medicine policies", group: "Medicine Control", description: "Create and edit medicine policies (reuse, return, retention).", scope: "both" },
  { key: "medicine.dispense.request", label: "Request medicine dispense", group: "Medicine Control", description: "Create dispense requests for patient/visit.", scope: "both" },
  { key: "medicine.dispense.approve", label: "Approve dispense requests", group: "Medicine Control", description: "Approve dispense requests (pharmacy).", scope: "both" },
  { key: "medicine.override.approve", label: "Approve medicine overrides", group: "Medicine Control", description: "Approve supervisor override requests (Manager/Owner only).", scope: "both" },
  { key: "medicine.dispense.issue", label: "Issue medicine", group: "Medicine Control", description: "Issue medicine from pharmacy (deduct stock).", scope: "both" },
  { key: "medicine.vial.open", label: "Open vial", group: "Medicine Control", description: "Open vial and start vial session.", scope: "both" },
  { key: "medicine.vial.activate", label: "Activate vial", group: "Medicine Control", description: "Allowed to activate vials in injection room (nurse, assistant, authorized doctor).", scope: "both" },
  { key: "medicine.vial.force_open", label: "Force open vial", group: "Medicine Control", description: "Override vial opening guard and open a new vial with explicit authorization.", scope: "both" },
  { key: "medicine.vial.use", label: "Log vial dose use", group: "Medicine Control", description: "Record dose consumption from open vial.", scope: "both" },
  { key: "medicine.vial.return", label: "Return vial", group: "Medicine Control", description: "Submit and close vial return.", scope: "both" },
  { key: "medicine.dose.record", label: "Record dose", group: "Medicine Control", description: "Record medication administration (dose).", scope: "both" },
  { key: "medicine.dose.read", label: "View dose records", group: "Medicine Control", description: "View medication administration records.", scope: "both" },
  { key: "injection.token.generate", label: "Generate injection token", group: "Medicine Control", description: "Generate anti-fraud injection tokens after billing.", scope: "both" },
  { key: "injection.token.validate", label: "Validate injection token", group: "Medicine Control", description: "Validate token before injection administration.", scope: "both" },
  { key: "injection.token.list", label: "View injection tokens", group: "Medicine Control", description: "View and filter injection token lifecycle records.", scope: "both" },
  { key: "injection.token.cancel", label: "Cancel injection token", group: "Medicine Control", description: "Cancel pending injection tokens when treatment changes.", scope: "both" },
  { key: "injection.token.emergency_bypass", label: "Emergency injection bypass", group: "Medicine Control", description: "Allow emergency dose recording without token with audit trail.", scope: "both" },
  { key: "medicine.reconciliation.run", label: "Run reconciliation", group: "Medicine Control", description: "Execute branch daily reconciliation and mismatch detection.", scope: "both" },
  { key: "medicine.reconciliation.read", label: "View reconciliation", group: "Medicine Control", description: "View daily reconciliation logs and mismatch details.", scope: "both" },
  { key: "medicine.reconciliation.acknowledge", label: "Acknowledge reconciliation", group: "Medicine Control", description: "Manager acknowledgement for flagged reconciliation mismatches.", scope: "both" },
  { key: "medicine.return.submit", label: "Submit vial return", group: "Medicine Control", description: "Submit vial return for audit.", scope: "both" },
  { key: "medicine.return.verify", label: "Verify vial return", group: "Medicine Control", description: "Verify returned vials.", scope: "both" },
  { key: "medicine.audit.bin.view", label: "View audit bins", group: "Medicine Control", description: "View audit bins and items.", scope: "both" },
  { key: "medicine.audit.bin.manage", label: "Manage audit bins", group: "Medicine Control", description: "Create, seal, and manage audit bins.", scope: "both" },
  { key: "medicine.destruction.approve", label: "Approve destruction", group: "Medicine Control", description: "Approve and record destruction of held items.", scope: "both" },
  // ----- Admin Medicine Workspace (master catalog, imports hub) -----
  { key: "medicine.master.read", label: "View medicine master data", group: "Admin Medicine", description: "Dashboard, lists, and detail for generics, brands, listings, imports review.", scope: "admin" },
  { key: "medicine.master.write", label: "Manage medicine master data", group: "Admin Medicine", description: "Create/update/archive generics, forms, manufacturers, brands, presentations, listings.", scope: "admin" },
  { key: "medicine.catalog.listing.manage", label: "Manage country medicine listings", group: "Admin Medicine", description: "Create and edit country-scoped catalog rows (CountryMedicineBrand).", scope: "admin" },
  { key: "medicine.catalog.import", label: "Medicine catalog import", group: "Admin Medicine", description: "Upload, preview, confirm, and apply medicine CSV imports.", scope: "admin" },
  { key: "medicine.catalog.export", label: "Export medicine catalog", group: "Admin Medicine", description: "Export listings and batch-derived CSV exports.", scope: "admin" },
  { key: "medicine.catalog.review", label: "Medicine import review", group: "Admin Medicine", description: "Access review/conflict queues for import rows.", scope: "admin" },
  { key: "medicine.catalog.governance", label: "Medicine catalog governance", group: "Admin Medicine", description: "Elevated actions on master data and imports (super-admin style).", scope: "admin" },
  // ----- Clinic Setup (Owner Panel clinic pages) -----
  { key: "clinic.settings.read", label: "View clinic settings", group: "Clinic Setup", description: "View clinic settings (hours, specializations).", scope: "both" },
  { key: "clinic.settings.write", label: "Edit clinic settings", group: "Clinic Setup", description: "Edit clinic settings.", scope: "both" },
  { key: "clinic.services.manage", label: "Manage clinic services", group: "Clinic Setup", description: "Create, edit, delete clinic service catalog.", scope: "both" },
  { key: "clinic.overview.read", label: "View clinic overview", group: "Clinic Setup", description: "View clinic overview dashboard.", scope: "both" },
  { key: "clinic.rooms.manage", label: "Manage clinic rooms", group: "Clinic Setup", description: "Create, edit, deactivate clinic rooms/chambers.", scope: "both" },
  { key: "clinic.rooms.create", label: "Create clinic rooms", group: "Clinic Setup", description: "Create new clinic rooms.", scope: "both" },
  { key: "clinic.rooms.update", label: "Update clinic rooms", group: "Clinic Setup", description: "Update room details and operational status.", scope: "both" },
  { key: "clinic.rooms.assign", label: "Assign room to appointment", group: "Clinic Setup", description: "Assign room when booking.", scope: "both" },
  { key: "clinic.rooms.reassign", label: "Reassign room", group: "Clinic Setup", description: "Reassign room for an appointment.", scope: "both" },
  { key: "clinic.rooms.view_schedule", label: "View room schedule board", group: "Clinic Setup", description: "View room schedule board.", scope: "both" },
  { key: "clinic.rooms.view_live", label: "View live room monitor", group: "Clinic Setup", description: "View live room monitor.", scope: "both" },
  { key: "clinic.rooms.manage_blocks", label: "Manage room blocks", group: "Clinic Setup", description: "Create and release room blocks.", scope: "both" },
  { key: "clinic.rooms.mark_cleaning", label: "Mark room cleaning", group: "Clinic Setup", description: "Mark room as cleaning.", scope: "both" },
  { key: "clinic.rooms.mark_occupied", label: "Mark room occupied", group: "Clinic Setup", description: "Mark room occupied.", scope: "both" },
  { key: "clinic.rooms.deactivate", label: "Deactivate clinic room", group: "Clinic Setup", description: "Deactivate a clinic room.", scope: "both" },
  { key: "clinic.rooms.view_analytics", label: "View room analytics", group: "Clinic Setup", description: "View room utilization analytics.", scope: "both" },
  { key: "clinic.rooms.view_audit", label: "View room audit", group: "Clinic Setup", description: "View room audit history.", scope: "both" },
  { key: "clinic.rooms.emergency_override", label: "Emergency override room", group: "Clinic Setup", description: "Emergency override room status (with audit).", scope: "both" },
  { key: "clinic.rooms.approve_changes", label: "Approve room changes", group: "Clinic Setup", description: "Approve room change requests.", scope: "both" },
  { key: "clinic.staff.manage", label: "Manage clinic staff profiles", group: "Clinic Setup", description: "Edit clinic staff profiles (type, license, fee, template).", scope: "both" },
  { key: "clinic.schedule.manage", label: "Manage clinic schedule templates", group: "Clinic Setup", description: "Edit doctor and room schedule templates.", scope: "both" },
  { key: "clinic.holidays.manage", label: "Manage clinic holidays", group: "Clinic Setup", description: "Add and remove branch holidays.", scope: "both" },
  { key: "clinic.emergency.manage", label: "Manage emergency slot policy", group: "Clinic Setup", description: "Configure emergency slot policy.", scope: "both" },
  { key: "clinic.fees.manage", label: "Manage clinic fees", group: "Clinic Setup", description: "Configure service fee overrides and view doctor fees.", scope: "both" },
  // ----- Clinical catalog (item master: medicines, consumables, instruments) -----
  { key: "catalog.manage", label: "Manage clinical catalog", group: "Clinical Catalog", description: "Admin: view and govern clinical item catalog.", scope: "admin" },
  { key: "catalog.category.manage", label: "Manage catalog categories", group: "Clinical Catalog", description: "Admin: manage clinical item categories.", scope: "admin" },
  { key: "catalog.audit.read", label: "View catalog audit", group: "Clinical Catalog", description: "Admin: view clinical item audit logs.", scope: "admin" },
  { key: "catalog.approval.manage", label: "Manage catalog approvals", group: "Clinical Catalog", description: "Admin: approve or reject clinical item requests.", scope: "admin" },
  { key: "clinic.items.read", label: "View clinical items", group: "Clinical Catalog", description: "View clinical catalog items and search.", scope: "both" },
  { key: "clinic.items.manage", label: "Manage clinical items", group: "Clinical Catalog", description: "Create, edit, activate/deactivate clinical items and categories.", scope: "both" },
  { key: "clinic.catalog.install", label: "Install catalog template", group: "Clinical Catalog", description: "Install master catalog template to clinic (org).", scope: "both" },
  { key: "clinic.stock.read", label: "View clinical stock", group: "Clinical Catalog", description: "View branch clinical item stock and low-stock alerts.", scope: "both" },
  // ----- Clinic Supply Chain (enterprise plan) -----
  { key: "clinic.supply.request.create", label: "Create supply request", group: "Clinic Supply Chain", description: "Create draft clinical supply request.", scope: "both" },
  { key: "clinic.supply.request.submit", label: "Submit supply request", group: "Clinic Supply Chain", description: "Submit supply request for owner review.", scope: "both" },
  { key: "clinic.supply.request.review", label: "Review supply request", group: "Clinic Supply Chain", description: "Owner: approve, reject, or modify supply requests.", scope: "both" },
  { key: "clinic.supply.transfer.dispatch", label: "Dispatch transfer", group: "Clinic Supply Chain", description: "Owner: dispatch clinical stock transfer.", scope: "both" },
  { key: "clinic.supply.transfer.receive", label: "Receive transfer", group: "Clinic Supply Chain", description: "Receive clinical stock transfer at branch.", scope: "both" },
  { key: "clinic.sterilization.manage", label: "Manage sterilization", group: "Clinic Supply Chain", description: "Start/complete sterilization cycles and view instruments.", scope: "both" },
  { key: "clinic.instrument.manage", label: "Manage instruments", group: "Clinic Supply Chain", description: "CRUD instrument instances and usage.", scope: "both" },
  { key: "clinic.audit.create", label: "Create stock audit", group: "Clinic Supply Chain", description: "Owner: create and run clinical stock audits.", scope: "both" },
  { key: "clinic.audit.approve", label: "Approve stock audit", group: "Clinic Supply Chain", description: "Owner: approve audit and post adjustments.", scope: "both" },
  { key: "clinic.wastage.report", label: "Report wastage", group: "Clinic Supply Chain", description: "Report clinical item wastage (expired, damaged, etc.).", scope: "both" },
  { key: "clinic.wastage.approve", label: "Approve wastage", group: "Clinic Supply Chain", description: "Owner: approve wastage and deduct stock.", scope: "both" },
  { key: "clinic.refill.view", label: "View refill suggestions", group: "Clinic Supply Chain", description: "View replenishment recommendations.", scope: "both" },
  { key: "clinic.refill.convert", label: "Convert to supply request", group: "Clinic Supply Chain", description: "Convert replenishment recommendations to supply request.", scope: "both" },
  // ----- Country (permissionMenu country) — used in country panel and admin country governance -----
  { key: "country.dashboard.read", label: "Country dashboard", group: "Country Governance", description: "View country dashboard.", scope: "admin" },
  { key: "country.operations.read", label: "Country operations", group: "Country Governance", description: "View country operations (adoptions, donations, etc.).", scope: "admin" },
  { key: "country.moderation.read", label: "Country moderation", group: "Country Governance", description: "Content moderation at country level.", scope: "admin" },
  { key: "country.support.read", label: "Country support", group: "Country Governance", description: "Support tickets at country level.", scope: "admin" },
  { key: "country.orgs.read", label: "Country organizations", group: "Country Governance", description: "View organizations in country scope.", scope: "admin" },
  { key: "country.staff.read", label: "Country staff", group: "Country Governance", description: "View country staff.", scope: "admin" },
  { key: "country.staff.invite", label: "Country staff invite", group: "Country Governance", description: "Invite country staff.", scope: "admin" },
  { key: "country.compliance.read", label: "Country compliance", group: "Country Governance", description: "Compliance center.", scope: "admin" },
  { key: "country.reports.read", label: "Country reports", group: "Country Governance", description: "Country reports.", scope: "admin" },
  { key: "country.audit.read", label: "Country audit", group: "Country Governance", description: "Country audit logs.", scope: "admin" },
  { key: "country.profile.read", label: "Country profile", group: "Country Governance", description: "Country profile.", scope: "admin" },
  { key: "country.settings.features.read", label: "Country feature toggles", group: "Country Governance", description: "View country feature toggles.", scope: "admin" },
  { key: "country.settings.policies.read", label: "Country policies", group: "Country Governance", description: "View country policy rules.", scope: "admin" },
  // ----- Manager Operations (Branch Manager Control) -----
  { key: "manager.appointments.create", label: "Create appointments", group: "Manager Operations", description: "Create clinic appointments.", scope: "both" },
  { key: "manager.appointments.assign_doctor", label: "Assign doctor", group: "Manager Operations", description: "Assign doctor to appointments.", scope: "both" },
  { key: "manager.appointments.cancel", label: "Cancel appointments", group: "Manager Operations", description: "Cancel appointments.", scope: "both" },
  { key: "manager.appointments.reschedule", label: "Reschedule appointments", group: "Manager Operations", description: "Reschedule appointments.", scope: "both" },
  { key: "manager.walkin.register", label: "Register walk-in", group: "Manager Operations", description: "Register walk-in patients.", scope: "both" },
  { key: "manager.patients.create", label: "Create patients", group: "Manager Operations", description: "Create patient/pet records.", scope: "both" },
  { key: "manager.patients.edit", label: "Edit patients", group: "Manager Operations", description: "Edit patient/pet records.", scope: "both" },
  { key: "manager.patients.view_history", label: "View patient history", group: "Manager Operations", description: "View full patient visit history.", scope: "both" },
  { key: "manager.inventory.update_stock", label: "Update stock", group: "Manager Operations", description: "Update branch inventory stock.", scope: "both" },
  { key: "manager.inventory.supply_request", label: "Supply request", group: "Manager Operations", description: "Create supply requests.", scope: "both" },
  { key: "manager.inventory.purchase_request", label: "Purchase request", group: "Manager Operations", description: "Create purchase requests.", scope: "both" },
  { key: "manager.inventory.low_stock_alert", label: "Low stock alert", group: "Manager Operations", description: "View and act on low stock alerts.", scope: "both" },
  { key: "manager.services.enable_disable", label: "Enable/disable services", group: "Manager Operations", description: "Enable or disable branch-level services.", scope: "both" },
  { key: "manager.packages.activate", label: "Activate packages", group: "Manager Operations", description: "Activate packages at branch.", scope: "both" },
  { key: "manager.discount.apply", label: "Apply discount", group: "Manager Operations", description: "Apply discount within policy limit.", scope: "both" },
  { key: "manager.pricing.view", label: "View pricing", group: "Manager Operations", description: "View branch pricing.", scope: "both" },
  { key: "manager.staff.assign", label: "Assign staff", group: "Manager Operations", description: "Assign staff to branch/shifts.", scope: "both" },
  { key: "manager.staff.duty_roster", label: "Duty roster", group: "Manager Operations", description: "Manage duty roster.", scope: "both" },
  { key: "manager.staff.leave_approve", label: "Approve leave", group: "Manager Operations", description: "Approve staff leave requests.", scope: "both" },
  { key: "manager.staff.performance_view", label: "View staff performance", group: "Manager Operations", description: "View staff performance metrics.", scope: "both" },
  { key: "manager.billing.create_invoice", label: "Create invoice", group: "Manager Operations", description: "Create invoices.", scope: "both" },
  { key: "manager.billing.collect_payment", label: "Collect payment", group: "Manager Operations", description: "Collect payments.", scope: "both" },
  { key: "manager.billing.refund_request", label: "Refund request", group: "Manager Operations", description: "Request refund within policy.", scope: "both" },
  { key: "manager.reports.daily_revenue", label: "Daily revenue report", group: "Manager Operations", description: "View daily revenue report.", scope: "both" },
  { key: "manager.reports.doctor_performance", label: "Doctor performance report", group: "Manager Operations", description: "View doctor performance.", scope: "both" },
  { key: "manager.reports.inventory_usage", label: "Inventory usage report", group: "Manager Operations", description: "View inventory usage.", scope: "both" },
  { key: "manager.reports.export", label: "Export reports", group: "Manager Operations", description: "Export manager reports.", scope: "both" },
  { key: "manager.branch.settings", label: "Branch settings", group: "Manager Operations", description: "View/edit branch settings within policy.", scope: "both" },
  { key: "manager.branch.hours", label: "Branch hours", group: "Manager Operations", description: "View/edit branch hours.", scope: "both" },
  { key: "manager.branch.announcements", label: "Branch announcements", group: "Manager Operations", description: "Manage branch announcements.", scope: "both" },
];

const GROUP_ORDER: string[] = [
  "Governance",
  "Support",
  "Producer",
  "Batch",
  "Product",
  "Printing",
  "Codes",
  "KYC",
  "My Business",
  "Products",
  "Inventory",
  "Orders",
  "People",
  "Reports",
  "Settings",
  "Staff Branch",
  "Clinic",
  "Medicine Control",
  "Clinic Setup",
  "Clinical Catalog",
  "Clinic Supply Chain",
  "Country Governance",
  "Manager Operations",
];

/**
 * Returns permissions grouped by group key, in stable order.
 * Does not hit DB; registry is read-only and derived from UI/spec.
 */
export function getGroupedRegistry(): { group: string; permissions: PermissionEntry[] }[] {
  const byGroup = new Map<string, PermissionEntry[]>();
  for (const p of REGISTRY) {
    const list = byGroup.get(p.group) ?? [];
    list.push(p);
    byGroup.set(p.group, list);
  }
  const seen = new Set<string>();
  const ordered: { group: string; permissions: PermissionEntry[] }[] = [];
  for (const g of GROUP_ORDER) {
    if (byGroup.has(g) && !seen.has(g)) {
      seen.add(g);
      ordered.push({ group: g, permissions: byGroup.get(g)! });
    }
  }
  for (const [g, perms] of byGroup) {
    if (!seen.has(g)) ordered.push({ group: g, permissions: perms });
  }
  return ordered;
}
